# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/coreBQ6471.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.bplr_page = QtWidgets.QWidget()
        self.bplr_page.setObjectName("bplr_page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.bplr_page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 60, 611, 589))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bplr_title_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_title_label.setFont(font)
        self.bplr_title_label.setObjectName("bplr_title_label")
        self.gridLayout.addWidget(self.bplr_title_label, 0, 0, 1, 1)
        self.bplr_housenumber_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_housenumber_lineedit.setObjectName("bplr_housenumber_lineedit")
        self.gridLayout.addWidget(self.bplr_housenumber_lineedit, 3, 1, 1, 1)
        self.bplr_house_price_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_house_price_lineedit.setObjectName("bplr_house_price_lineedit")
        self.gridLayout.addWidget(self.bplr_house_price_lineedit, 5, 0, 1, 1)
        self.bplr_postcode_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_postcode_label.setFont(font)
        self.bplr_postcode_label.setObjectName("bplr_postcode_label")
        self.gridLayout.addWidget(self.bplr_postcode_label, 2, 0, 1, 1)
        self.bplr_postcode_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_postcode_lineedit.setObjectName("bplr_postcode_lineedit")
        self.gridLayout.addWidget(self.bplr_postcode_lineedit, 3, 0, 1, 1)
        self.bplr_seller_phone_number_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_seller_phone_number_lineedit.setObjectName("bplr_seller_phone_number_lineedit")
        self.gridLayout.addWidget(self.bplr_seller_phone_number_lineedit, 8, 0, 1, 1)
        self.bplr_house_link_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_house_link_lineedit.setObjectName("bplr_house_link_lineedit")
        self.gridLayout.addWidget(self.bplr_house_link_lineedit, 5, 1, 1, 1)
        self.bplr_submit_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bplr_submit_button.setObjectName("bplr_submit_button")
        self.gridLayout.addWidget(self.bplr_submit_button, 18, 1, 1, 1)
        self.bplr_mortgage_information_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_mortgage_information_label.setFont(font)
        self.bplr_mortgage_information_label.setObjectName("bplr_mortgage_information_label")
        self.gridLayout.addWidget(self.bplr_mortgage_information_label, 9, 0, 1, 1)
        self.bplr_amount_wanted_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_amount_wanted_lineedit.setObjectName("bplr_amount_wanted_lineedit")
        self.gridLayout.addWidget(self.bplr_amount_wanted_lineedit, 11, 0, 1, 1)
        self.bplr_housenumber_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_housenumber_label.setFont(font)
        self.bplr_housenumber_label.setObjectName("bplr_housenumber_label")
        self.gridLayout.addWidget(self.bplr_housenumber_label, 2, 1, 1, 1)
        self.bplr_mortgage_type_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_mortgage_type_label.setFont(font)
        self.bplr_mortgage_type_label.setObjectName("bplr_mortgage_type_label")
        self.gridLayout.addWidget(self.bplr_mortgage_type_label, 10, 1, 1, 1)
        self.bplr_house_price_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_house_price_label.setFont(font)
        self.bplr_house_price_label.setObjectName("bplr_house_price_label")
        self.gridLayout.addWidget(self.bplr_house_price_label, 4, 0, 1, 1)
        self.bplr_preferred_banks_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bplr_preferred_banks_label.setObjectName("bplr_preferred_banks_label")
        self.gridLayout.addWidget(self.bplr_preferred_banks_label, 12, 0, 1, 1)
        self.bplr_seller_phone_number_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bplr_seller_phone_number_label.setObjectName("bplr_seller_phone_number_label")
        self.gridLayout.addWidget(self.bplr_seller_phone_number_label, 7, 0, 1, 1)
        self.bplr_amount_wanted_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_amount_wanted_label.setFont(font)
        self.bplr_amount_wanted_label.setObjectName("bplr_amount_wanted_label")
        self.gridLayout.addWidget(self.bplr_amount_wanted_label, 10, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bplr_linear_radiobutton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.bplr_linear_radiobutton.setChecked(True)
        self.bplr_linear_radiobutton.setObjectName("bplr_linear_radiobutton")
        self.gridLayout_2.addWidget(self.bplr_linear_radiobutton, 0, 0, 1, 1)
        self.bplr_fixedrate_radiobutton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.bplr_fixedrate_radiobutton.setObjectName("bplr_fixedrate_radiobutton")
        self.gridLayout_2.addWidget(self.bplr_fixedrate_radiobutton, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 11, 1, 1, 1)
        self.bplr_house_link_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_house_link_label.setFont(font)
        self.bplr_house_link_label.setObjectName("bplr_house_link_label")
        self.gridLayout.addWidget(self.bplr_house_link_label, 4, 1, 1, 1)
        self.bplr_property_information_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_property_information_label.setFont(font)
        self.bplr_property_information_label.setObjectName("bplr_property_information_label")
        self.gridLayout.addWidget(self.bplr_property_information_label, 1, 0, 1, 1)
        self.bplr_description_textedit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.bplr_description_textedit.setObjectName("bplr_description_textedit")
        self.gridLayout.addWidget(self.bplr_description_textedit, 17, 0, 1, 2)
        self.bplr_description_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.bplr_description_label.setFont(font)
        self.bplr_description_label.setObjectName("bplr_description_label")
        self.gridLayout.addWidget(self.bplr_description_label, 16, 0, 1, 2)
        self.bplr_personal_information_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_personal_information_label.setFont(font)
        self.bplr_personal_information_label.setObjectName("bplr_personal_information_label")
        self.gridLayout.addWidget(self.bplr_personal_information_label, 15, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.bplr_bank2_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bplr_bank2_checkbox.setChecked(True)
        self.bplr_bank2_checkbox.setObjectName("bplr_bank2_checkbox")
        self.gridLayout_4.addWidget(self.bplr_bank2_checkbox, 0, 1, 1, 1)
        self.bplr_bank1_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bplr_bank1_checkbox.setObjectName("bplr_bank1_checkbox")
        self.gridLayout_4.addWidget(self.bplr_bank1_checkbox, 0, 0, 1, 1)
        self.bplr_bank3_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bplr_bank3_checkbox.setChecked(True)
        self.bplr_bank3_checkbox.setObjectName("bplr_bank3_checkbox")
        self.gridLayout_4.addWidget(self.bplr_bank3_checkbox, 1, 0, 1, 1)
        self.bplr_bank4_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bplr_bank4_checkbox.setObjectName("bplr_bank4_checkbox")
        self.gridLayout_4.addWidget(self.bplr_bank4_checkbox, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 14, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout.addLayout(self.gridLayout_5, 14, 1, 1, 1)
        self.bplr_property_seller_information_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_property_seller_information_label.setFont(font)
        self.bplr_property_seller_information_label.setObjectName("bplr_property_seller_information_label")
        self.gridLayout.addWidget(self.bplr_property_seller_information_label, 6, 0, 1, 1)
        self.bplr_seller_email_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bplr_seller_email_label.setObjectName("bplr_seller_email_label")
        self.gridLayout.addWidget(self.bplr_seller_email_label, 7, 1, 1, 1)
        self.bplr_seller_email_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_seller_email_lineedit.setObjectName("bplr_seller_email_lineedit")
        self.gridLayout.addWidget(self.bplr_seller_email_lineedit, 8, 1, 1, 1)
        self.prev_1 = QtWidgets.QToolButton(self.bplr_page)
        self.prev_1.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_1.setObjectName("prev_1")
        self.next_1 = QtWidgets.QToolButton(self.bplr_page)
        self.next_1.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_1.setObjectName("next_1")
        self.stackedWidget.addWidget(self.bplr_page)
        self.fiplr1_page = QtWidgets.QWidget()
        self.fiplr1_page.setObjectName("fiplr1_page")
        self.next_2 = QtWidgets.QToolButton(self.fiplr1_page)
        self.next_2.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_2.setObjectName("next_2")
        self.fiplr1_pending_loan_requests_label = QtWidgets.QLabel(self.fiplr1_page)
        self.fiplr1_pending_loan_requests_label.setGeometry(QtCore.QRect(60, 60, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr1_pending_loan_requests_label.setFont(font)
        self.fiplr1_pending_loan_requests_label.setObjectName("fiplr1_pending_loan_requests_label")
        self.fiplr1_loan_requests_table = QtWidgets.QTableWidget(self.fiplr1_page)
        self.fiplr1_loan_requests_table.setEnabled(True)
        self.fiplr1_loan_requests_table.setGeometry(QtCore.QRect(60, 120, 571, 221))
        self.fiplr1_loan_requests_table.setMaximumSize(QtCore.QSize(800, 16777215))
        self.fiplr1_loan_requests_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fiplr1_loan_requests_table.setDragEnabled(False)
        self.fiplr1_loan_requests_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.fiplr1_loan_requests_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fiplr1_loan_requests_table.setShowGrid(False)
        self.fiplr1_loan_requests_table.setWordWrap(False)
        self.fiplr1_loan_requests_table.setObjectName("fiplr1_loan_requests_table")
        self.fiplr1_loan_requests_table.setColumnCount(4)
        self.fiplr1_loan_requests_table.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.fiplr1_loan_requests_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setItem(0, 3, item)
        self.fiplr1_loan_requests_table.horizontalHeader().setDefaultSectionSize(138)
        self.fiplr1_loan_requests_table.verticalHeader().setDefaultSectionSize(30)
        self.fiplr1_view_loan_request_pushbutton = QtWidgets.QPushButton(self.fiplr1_page)
        self.fiplr1_view_loan_request_pushbutton.setGeometry(QtCore.QRect(510, 360, 121, 27))
        self.fiplr1_view_loan_request_pushbutton.setObjectName("fiplr1_view_loan_request_pushbutton")
        self.prev_2 = QtWidgets.QToolButton(self.fiplr1_page)
        self.prev_2.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_2.setObjectName("prev_2")
        self.stackedWidget.addWidget(self.fiplr1_page)
        self.fiplr2_page = QtWidgets.QWidget()
        self.fiplr2_page.setObjectName("fiplr2_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fiplr2_page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.fiplr2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -367, 823, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(1, 1000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_3.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.next_3 = QtWidgets.QToolButton(self.widget)
        self.next_3.setGeometry(QtCore.QRect(30, 0, 22, 25))
        self.next_3.setObjectName("next_3")
        self.fiplr2_lastname_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_lastname_lineedit.setEnabled(False)
        self.fiplr2_lastname_lineedit.setGeometry(QtCore.QRect(230, 190, 141, 27))
        self.fiplr2_lastname_lineedit.setObjectName("fiplr2_lastname_lineedit")
        self.fiplr2_property_value_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_property_value_lineedit.setEnabled(False)
        self.fiplr2_property_value_lineedit.setGeometry(QtCore.QRect(420, 580, 151, 27))
        self.fiplr2_property_value_lineedit.setObjectName("fiplr2_property_value_lineedit")
        self.fiplr2_risk_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_risk_lineedit.setEnabled(False)
        self.fiplr2_risk_lineedit.setGeometry(QtCore.QRect(230, 330, 51, 27))
        self.fiplr2_risk_lineedit.setObjectName("fiplr2_risk_lineedit")
        self.prev_3 = QtWidgets.QToolButton(self.widget)
        self.prev_3.setGeometry(QtCore.QRect(10, 0, 22, 25))
        self.prev_3.setObjectName("prev_3")
        self.fiplr2_property_address_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_property_address_label.setGeometry(QtCore.QRect(50, 480, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_property_address_label.setFont(font)
        self.fiplr2_property_address_label.setObjectName("fiplr2_property_address_label")
        self.fiplr2_lastname_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_lastname_label.setGeometry(QtCore.QRect(230, 160, 90, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_lastname_label.setFont(font)
        self.fiplr2_lastname_label.setObjectName("fiplr2_lastname_label")
        self.fiplr2_loan_amount_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_loan_amount_label.setGeometry(QtCore.QRect(420, 480, 211, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_loan_amount_label.setFont(font)
        self.fiplr2_loan_amount_label.setObjectName("fiplr2_loan_amount_label")
        self.fiplr2_reject_pushbutton = QtWidgets.QPushButton(self.widget)
        self.fiplr2_reject_pushbutton.setGeometry(QtCore.QRect(50, 940, 111, 31))
        self.fiplr2_reject_pushbutton.setObjectName("fiplr2_reject_pushbutton")
        self.fiplr2_offer_amount_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_offer_amount_lineedit.setGeometry(QtCore.QRect(50, 900, 141, 27))
        self.fiplr2_offer_amount_lineedit.setObjectName("fiplr2_offer_amount_lineedit")
        self.fiplr2_mortgage_information_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_mortgage_information_label.setGeometry(QtCore.QRect(50, 450, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_mortgage_information_label.setFont(font)
        self.fiplr2_mortgage_information_label.setObjectName("fiplr2_mortgage_information_label")
        self.fiplr2_email_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_email_label.setGeometry(QtCore.QRect(50, 370, 181, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_email_label.setFont(font)
        self.fiplr2_email_label.setObjectName("fiplr2_email_label")
        self.fiplr2_title_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_title_label.setGeometry(QtCore.QRect(50, 40, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_title_label.setFont(font)
        self.fiplr2_title_label.setObjectName("fiplr2_title_label")
        self.fiplr2_phonenumber_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_phonenumber_label.setGeometry(QtCore.QRect(50, 300, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_phonenumber_label.setFont(font)
        self.fiplr2_phonenumber_label.setObjectName("fiplr2_phonenumber_label")
        self.fiplr2_documents_listview = QtWidgets.QListView(self.widget)
        self.fiplr2_documents_listview.setGeometry(QtCore.QRect(420, 190, 281, 231))
        self.fiplr2_documents_listview.setObjectName("fiplr2_documents_listview")
        self.fiplr2_loan_request_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_loan_request_label.setGeometry(QtCore.QRect(50, 100, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_loan_request_label.setFont(font)
        self.fiplr2_loan_request_label.setObjectName("fiplr2_loan_request_label")
        self.fiplr2_loan_duration_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_loan_duration_label.setGeometry(QtCore.QRect(550, 870, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_loan_duration_label.setFont(font)
        self.fiplr2_loan_duration_label.setObjectName("fiplr2_loan_duration_label")
        self.fiplr2_loan_amount_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_loan_amount_lineedit.setEnabled(False)
        self.fiplr2_loan_amount_lineedit.setGeometry(QtCore.QRect(420, 510, 151, 27))
        self.fiplr2_loan_amount_lineedit.setObjectName("fiplr2_loan_amount_lineedit")
        self.fiplr2_default_rate_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_default_rate_lineedit.setGeometry(QtCore.QRect(410, 900, 81, 27))
        self.fiplr2_default_rate_lineedit.setObjectName("fiplr2_default_rate_lineedit")
        self.fiplr2_firstname_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_firstname_label.setGeometry(QtCore.QRect(50, 160, 90, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_firstname_label.setFont(font)
        self.fiplr2_firstname_label.setObjectName("fiplr2_firstname_label")
        self.fiplr2_address_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_address_label.setGeometry(QtCore.QRect(50, 230, 370, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_address_label.setFont(font)
        self.fiplr2_address_label.setObjectName("fiplr2_address_label")
        self.fiplr2_loan_duration_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_loan_duration_lineedit.setGeometry(QtCore.QRect(550, 900, 131, 27))
        self.fiplr2_loan_duration_lineedit.setObjectName("fiplr2_loan_duration_lineedit")
        self.fiplr2_mortgage_type_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_mortgage_type_lineedit.setEnabled(False)
        self.fiplr2_mortgage_type_lineedit.setGeometry(QtCore.QRect(50, 580, 151, 27))
        self.fiplr2_mortgage_type_lineedit.setObjectName("fiplr2_mortgage_type_lineedit")
        self.fiplr2_address_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_address_lineedit.setEnabled(False)
        self.fiplr2_address_lineedit.setGeometry(QtCore.QRect(50, 260, 321, 27))
        self.fiplr2_address_lineedit.setObjectName("fiplr2_address_lineedit")
        self.fiplr2_offer_amount_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_offer_amount_label.setGeometry(QtCore.QRect(50, 870, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_offer_amount_label.setFont(font)
        self.fiplr2_offer_amount_label.setObjectName("fiplr2_offer_amount_label")
        self.fiplr2_offer_interest_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_offer_interest_lineedit.setGeometry(QtCore.QRect(270, 900, 81, 27))
        self.fiplr2_offer_interest_lineedit.setObjectName("fiplr2_offer_interest_lineedit")
        self.fiplr2_phonenumber_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_phonenumber_lineedit.setEnabled(False)
        self.fiplr2_phonenumber_lineedit.setGeometry(QtCore.QRect(50, 330, 141, 27))
        self.fiplr2_phonenumber_lineedit.setObjectName("fiplr2_phonenumber_lineedit")
        self.fiplr2_personal_information_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_personal_information_label.setGeometry(QtCore.QRect(50, 130, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_personal_information_label.setFont(font)
        self.fiplr2_personal_information_label.setObjectName("fiplr2_personal_information_label")
        self.fiplr2_risk_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_risk_label.setGeometry(QtCore.QRect(230, 300, 121, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_risk_label.setFont(font)
        self.fiplr2_risk_label.setObjectName("fiplr2_risk_label")
        self.fiplr2_documents_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_documents_label.setGeometry(QtCore.QRect(420, 160, 90, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_documents_label.setFont(font)
        self.fiplr2_documents_label.setObjectName("fiplr2_documents_label")
        self.fiplr2_make_offer_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_make_offer_label.setGeometry(QtCore.QRect(50, 840, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_make_offer_label.setFont(font)
        self.fiplr2_make_offer_label.setObjectName("fiplr2_make_offer_label")
        self.fiplr2_property_address_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_property_address_lineedit.setEnabled(False)
        self.fiplr2_property_address_lineedit.setGeometry(QtCore.QRect(50, 510, 321, 27))
        self.fiplr2_property_address_lineedit.setObjectName("fiplr2_property_address_lineedit")
        self.fiplr2_email_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_email_lineedit.setEnabled(False)
        self.fiplr2_email_lineedit.setGeometry(QtCore.QRect(50, 400, 321, 27))
        self.fiplr2_email_lineedit.setObjectName("fiplr2_email_lineedit")
        self.fiplr2_default_rate_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_default_rate_label.setGeometry(QtCore.QRect(410, 870, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_default_rate_label.setFont(font)
        self.fiplr2_default_rate_label.setObjectName("fiplr2_default_rate_label")
        self.fiplr2_property_value_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_property_value_label.setGeometry(QtCore.QRect(420, 550, 370, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_property_value_label.setFont(font)
        self.fiplr2_property_value_label.setObjectName("fiplr2_property_value_label")
        self.fiplr2_firstname_lineedit = QtWidgets.QLineEdit(self.widget)
        self.fiplr2_firstname_lineedit.setEnabled(False)
        self.fiplr2_firstname_lineedit.setGeometry(QtCore.QRect(50, 190, 141, 27))
        self.fiplr2_firstname_lineedit.setObjectName("fiplr2_firstname_lineedit")
        self.fiplr2_accept_pushbutton = QtWidgets.QPushButton(self.widget)
        self.fiplr2_accept_pushbutton.setGeometry(QtCore.QRect(570, 940, 111, 31))
        self.fiplr2_accept_pushbutton.setObjectName("fiplr2_accept_pushbutton")
        self.fiplr2_offer_interest_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_offer_interest_label.setGeometry(QtCore.QRect(270, 870, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_offer_interest_label.setFont(font)
        self.fiplr2_offer_interest_label.setObjectName("fiplr2_offer_interest_label")
        self.fiplr2_mortgage_type_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_mortgage_type_label.setGeometry(QtCore.QRect(50, 550, 281, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_mortgage_type_label.setFont(font)
        self.fiplr2_mortgage_type_label.setObjectName("fiplr2_mortgage_type_label")
        self.fiplr2_description_textedit = QtWidgets.QTextEdit(self.widget)
        self.fiplr2_description_textedit.setEnabled(False)
        self.fiplr2_description_textedit.setGeometry(QtCore.QRect(50, 670, 651, 131))
        self.fiplr2_description_textedit.setStyleSheet("background-color: rgb(220, 220, 220)")
        self.fiplr2_description_textedit.setUndoRedoEnabled(False)
        self.fiplr2_description_textedit.setObjectName("fiplr2_description_textedit")
        self.fiplr2_description_label = QtWidgets.QLabel(self.widget)
        self.fiplr2_description_label.setGeometry(QtCore.QRect(50, 643, 131, 17))
        self.fiplr2_description_label.setObjectName("fiplr2_description_label")
        self.horizontalLayout_3.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.fiplr2_page)
        self.openmarket_page = QtWidgets.QWidget()
        self.openmarket_page.setObjectName("openmarket_page")
        self.openmarket_view_loan_bids_pushbutton = QtWidgets.QPushButton(self.openmarket_page)
        self.openmarket_view_loan_bids_pushbutton.setGeometry(QtCore.QRect(630, 490, 111, 22))
        self.openmarket_view_loan_bids_pushbutton.setObjectName("openmarket_view_loan_bids_pushbutton")
        self.openmarket_duration_label = QtWidgets.QLabel(self.openmarket_page)
        self.openmarket_duration_label.setGeometry(QtCore.QRect(630, 300, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_duration_label.setFont(font)
        self.openmarket_duration_label.setObjectName("openmarket_duration_label")
        self.next_4 = QtWidgets.QToolButton(self.openmarket_page)
        self.next_4.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_4.setObjectName("next_4")
        self.openmarket_min_amount_lineedit = QtWidgets.QLineEdit(self.openmarket_page)
        self.openmarket_min_amount_lineedit.setGeometry(QtCore.QRect(630, 220, 113, 20))
        self.openmarket_min_amount_lineedit.setObjectName("openmarket_min_amount_lineedit")
        self.openmarket_rating_checkbox_b = QtWidgets.QCheckBox(self.openmarket_page)
        self.openmarket_rating_checkbox_b.setGeometry(QtCore.QRect(630, 390, 70, 17))
        self.openmarket_rating_checkbox_b.setObjectName("openmarket_rating_checkbox_b")
        self.openmarket_interest_label = QtWidgets.QLabel(self.openmarket_page)
        self.openmarket_interest_label.setGeometry(QtCore.QRect(630, 250, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_interest_label.setFont(font)
        self.openmarket_interest_label.setObjectName("openmarket_interest_label")
        self.openmarket_search_lineedit = QtWidgets.QLineEdit(self.openmarket_page)
        self.openmarket_search_lineedit.setGeometry(QtCore.QRect(630, 110, 121, 21))
        self.openmarket_search_lineedit.setObjectName("openmarket_search_lineedit")
        self.openmarket_max_amount_lineedit = QtWidgets.QLineEdit(self.openmarket_page)
        self.openmarket_max_amount_lineedit.setGeometry(QtCore.QRect(630, 190, 113, 20))
        self.openmarket_max_amount_lineedit.setObjectName("openmarket_max_amount_lineedit")
        self.openmarket_interest1_lineedit = QtWidgets.QLineEdit(self.openmarket_page)
        self.openmarket_interest1_lineedit.setGeometry(QtCore.QRect(630, 270, 41, 20))
        self.openmarket_interest1_lineedit.setObjectName("openmarket_interest1_lineedit")
        self.openmarket_duration2_lineedit = QtWidgets.QLineEdit(self.openmarket_page)
        self.openmarket_duration2_lineedit.setGeometry(QtCore.QRect(690, 320, 41, 20))
        self.openmarket_duration2_lineedit.setObjectName("openmarket_duration2_lineedit")
        self.openmarket_interest_dash_label = QtWidgets.QLabel(self.openmarket_page)
        self.openmarket_interest_dash_label.setGeometry(QtCore.QRect(680, 270, 16, 16))
        self.openmarket_interest_dash_label.setObjectName("openmarket_interest_dash_label")
        self.openmarket_rating_checkbox_c = QtWidgets.QCheckBox(self.openmarket_page)
        self.openmarket_rating_checkbox_c.setGeometry(QtCore.QRect(630, 410, 70, 17))
        self.openmarket_rating_checkbox_c.setObjectName("openmarket_rating_checkbox_c")
        self.openmarket_duration_dash_label = QtWidgets.QLabel(self.openmarket_page)
        self.openmarket_duration_dash_label.setGeometry(QtCore.QRect(680, 320, 16, 16))
        self.openmarket_duration_dash_label.setObjectName("openmarket_duration_dash_label")
        self.openmarket_search_pushbutton = QtWidgets.QPushButton(self.openmarket_page)
        self.openmarket_search_pushbutton.setGeometry(QtCore.QRect(750, 110, 75, 21))
        self.openmarket_search_pushbutton.setObjectName("openmarket_search_pushbutton")
        self.prev_4 = QtWidgets.QToolButton(self.openmarket_page)
        self.prev_4.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_4.setObjectName("prev_4")
        self.openmarket_rating_label = QtWidgets.QLabel(self.openmarket_page)
        self.openmarket_rating_label.setGeometry(QtCore.QRect(630, 350, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_rating_label.setFont(font)
        self.openmarket_rating_label.setObjectName("openmarket_rating_label")
        self.openmarket_sorting_options_label = QtWidgets.QLabel(self.openmarket_page)
        self.openmarket_sorting_options_label.setGeometry(QtCore.QRect(630, 140, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_sorting_options_label.setFont(font)
        self.openmarket_sorting_options_label.setObjectName("openmarket_sorting_options_label")
        self.openmarket_title_label = QtWidgets.QLabel(self.openmarket_page)
        self.openmarket_title_label.setGeometry(QtCore.QRect(60, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_title_label.setFont(font)
        self.openmarket_title_label.setObjectName("openmarket_title_label")
        self.openmarket_rating_checkbox_a = QtWidgets.QCheckBox(self.openmarket_page)
        self.openmarket_rating_checkbox_a.setGeometry(QtCore.QRect(630, 370, 70, 17))
        self.openmarket_rating_checkbox_a.setObjectName("openmarket_rating_checkbox_a")
        self.openmarket_amount_label = QtWidgets.QLabel(self.openmarket_page)
        self.openmarket_amount_label.setGeometry(QtCore.QRect(630, 170, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_amount_label.setFont(font)
        self.openmarket_amount_label.setObjectName("openmarket_amount_label")
        self.openmarket_duration1_lineedit = QtWidgets.QLineEdit(self.openmarket_page)
        self.openmarket_duration1_lineedit.setGeometry(QtCore.QRect(630, 320, 41, 20))
        self.openmarket_duration1_lineedit.setObjectName("openmarket_duration1_lineedit")
        self.openmarket_interest2_lineedit = QtWidgets.QLineEdit(self.openmarket_page)
        self.openmarket_interest2_lineedit.setGeometry(QtCore.QRect(690, 270, 41, 20))
        self.openmarket_interest2_lineedit.setObjectName("openmarket_interest2_lineedit")
        self.openmarket_open_market_table = QtWidgets.QTableWidget(self.openmarket_page)
        self.openmarket_open_market_table.setGeometry(QtCore.QRect(60, 110, 541, 401))
        self.openmarket_open_market_table.setMaximumSize(QtCore.QSize(641, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_open_market_table.setFont(font)
        self.openmarket_open_market_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.openmarket_open_market_table.setAlternatingRowColors(False)
        self.openmarket_open_market_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.openmarket_open_market_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.openmarket_open_market_table.setShowGrid(False)
        self.openmarket_open_market_table.setGridStyle(QtCore.Qt.DotLine)
        self.openmarket_open_market_table.setObjectName("openmarket_open_market_table")
        self.openmarket_open_market_table.setColumnCount(5)
        self.openmarket_open_market_table.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.openmarket_open_market_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.openmarket_open_market_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.openmarket_open_market_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.openmarket_open_market_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setItem(1, 4, item)
        self.openmarket_open_market_table.horizontalHeader().setDefaultSectionSize(110)
        self.openmarket_open_market_table.horizontalHeader().setStretchLastSection(True)
        self.openmarket_open_market_table.verticalHeader().setStretchLastSection(False)
        self.stackedWidget.addWidget(self.openmarket_page)
        self.icb_page = QtWidgets.QWidget()
        self.icb_page.setObjectName("icb_page")
        self.icb_amount_lineedit = QtWidgets.QLineEdit(self.icb_page)
        self.icb_amount_lineedit.setGeometry(QtCore.QRect(60, 510, 113, 27))
        self.icb_amount_lineedit.setObjectName("icb_amount_lineedit")
        self.icb_property_address_lineedit = QtWidgets.QLineEdit(self.icb_page)
        self.icb_property_address_lineedit.setEnabled(False)
        self.icb_property_address_lineedit.setGeometry(QtCore.QRect(60, 130, 421, 27))
        self.icb_property_address_lineedit.setObjectName("icb_property_address_lineedit")
        self.icb_duration_lineedit = QtWidgets.QLineEdit(self.icb_page)
        self.icb_duration_lineedit.setGeometry(QtCore.QRect(330, 510, 113, 27))
        self.icb_duration_lineedit.setObjectName("icb_duration_lineedit")
        self.icb_duration_label = QtWidgets.QLabel(self.icb_page)
        self.icb_duration_label.setGeometry(QtCore.QRect(330, 490, 121, 17))
        self.icb_duration_label.setObjectName("icb_duration_label")
        self.icb_current_bids_table = QtWidgets.QTableWidget(self.icb_page)
        self.icb_current_bids_table.setGeometry(QtCore.QRect(60, 200, 631, 231))
        self.icb_current_bids_table.setMaximumSize(QtCore.QSize(900, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.icb_current_bids_table.setFont(font)
        self.icb_current_bids_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.icb_current_bids_table.setAlternatingRowColors(False)
        self.icb_current_bids_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.icb_current_bids_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.icb_current_bids_table.setShowGrid(False)
        self.icb_current_bids_table.setGridStyle(QtCore.Qt.DotLine)
        self.icb_current_bids_table.setObjectName("icb_current_bids_table")
        self.icb_current_bids_table.setColumnCount(3)
        self.icb_current_bids_table.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.icb_current_bids_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.icb_current_bids_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.icb_current_bids_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.icb_current_bids_table.setItem(0, 2, item)
        self.icb_current_bids_table.horizontalHeader().setDefaultSectionSize(110)
        self.icb_current_bids_table.horizontalHeader().setStretchLastSection(True)
        self.icb_current_bids_table.verticalHeader().setStretchLastSection(False)
        self.icb_place_bid_label = QtWidgets.QLabel(self.icb_page)
        self.icb_place_bid_label.setGeometry(QtCore.QRect(60, 460, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.icb_place_bid_label.setFont(font)
        self.icb_place_bid_label.setObjectName("icb_place_bid_label")
        self.icb_amount_label = QtWidgets.QLabel(self.icb_page)
        self.icb_amount_label.setGeometry(QtCore.QRect(60, 490, 121, 17))
        self.icb_amount_label.setObjectName("icb_amount_label")
        self.icb_place_bid_pushbutton = QtWidgets.QPushButton(self.icb_page)
        self.icb_place_bid_pushbutton.setGeometry(QtCore.QRect(580, 580, 111, 27))
        self.icb_place_bid_pushbutton.setObjectName("icb_place_bid_pushbutton")
        self.icb_current_bids_label = QtWidgets.QLabel(self.icb_page)
        self.icb_current_bids_label.setGeometry(QtCore.QRect(60, 180, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.icb_current_bids_label.setFont(font)
        self.icb_current_bids_label.setObjectName("icb_current_bids_label")
        self.icb_interest_label = QtWidgets.QLabel(self.icb_page)
        self.icb_interest_label.setGeometry(QtCore.QRect(580, 490, 191, 17))
        self.icb_interest_label.setObjectName("icb_interest_label")
        self.icb_interest_lineedit = QtWidgets.QLineEdit(self.icb_page)
        self.icb_interest_lineedit.setGeometry(QtCore.QRect(580, 510, 113, 27))
        self.icb_interest_lineedit.setObjectName("icb_interest_lineedit")
        self.icb_title_label = QtWidgets.QLabel(self.icb_page)
        self.icb_title_label.setGeometry(QtCore.QRect(60, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.icb_title_label.setFont(font)
        self.icb_title_label.setObjectName("icb_title_label")
        self.icb_property_address_label = QtWidgets.QLabel(self.icb_page)
        self.icb_property_address_label.setGeometry(QtCore.QRect(60, 110, 181, 17))
        self.icb_property_address_label.setObjectName("icb_property_address_label")
        self.prev_5 = QtWidgets.QToolButton(self.icb_page)
        self.prev_5.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_5.setObjectName("prev_5")
        self.next_5 = QtWidgets.QToolButton(self.icb_page)
        self.next_5.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_5.setObjectName("next_5")
        self.stackedWidget.addWidget(self.icb_page)
        self.ip_page = QtWidgets.QWidget()
        self.ip_page.setObjectName("ip_page")
        self.next_6 = QtWidgets.QToolButton(self.ip_page)
        self.next_6.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_6.setObjectName("next_6")
        self.ip_reject_pushbutton = QtWidgets.QPushButton(self.ip_page)
        self.ip_reject_pushbutton.setEnabled(False)
        self.ip_reject_pushbutton.setGeometry(QtCore.QRect(400, 1060, 75, 23))
        self.ip_reject_pushbutton.setObjectName("ip_reject_pushbutton")
        self.ip_interest1_lineedit = QtWidgets.QLineEdit(self.ip_page)
        self.ip_interest1_lineedit.setGeometry(QtCore.QRect(60, 260, 41, 20))
        self.ip_interest1_lineedit.setObjectName("ip_interest1_lineedit")
        self.ip_ongoing_investments_label = QtWidgets.QLabel(self.ip_page)
        self.ip_ongoing_investments_label.setGeometry(QtCore.QRect(60, 100, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ip_ongoing_investments_label.setFont(font)
        self.ip_ongoing_investments_label.setObjectName("ip_ongoing_investments_label")
        self.ip_investors_portfolio_label = QtWidgets.QLabel(self.ip_page)
        self.ip_investors_portfolio_label.setGeometry(QtCore.QRect(60, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ip_investors_portfolio_label.setFont(font)
        self.ip_investors_portfolio_label.setObjectName("ip_investors_portfolio_label")
        self.prev_6 = QtWidgets.QToolButton(self.ip_page)
        self.prev_6.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_6.setObjectName("prev_6")
        self.ip_investments_table = QtWidgets.QTableWidget(self.ip_page)
        self.ip_investments_table.setEnabled(True)
        self.ip_investments_table.setGeometry(QtCore.QRect(60, 300, 721, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_investments_table.sizePolicy().hasHeightForWidth())
        self.ip_investments_table.setSizePolicy(sizePolicy)
        self.ip_investments_table.setMaximumSize(QtCore.QSize(800, 16777215))
        self.ip_investments_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ip_investments_table.setDragEnabled(False)
        self.ip_investments_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ip_investments_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ip_investments_table.setShowGrid(False)
        self.ip_investments_table.setWordWrap(False)
        self.ip_investments_table.setObjectName("ip_investments_table")
        self.ip_investments_table.setColumnCount(6)
        self.ip_investments_table.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.ip_investments_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investments_table.setItem(0, 3, item)
        self.ip_investments_table.horizontalHeader().setDefaultSectionSize(138)
        self.ip_investments_table.verticalHeader().setDefaultSectionSize(30)
        self.ip_investing_opportunities_table = QtWidgets.QTableWidget(self.ip_page)
        self.ip_investing_opportunities_table.setEnabled(False)
        self.ip_investing_opportunities_table.setGeometry(QtCore.QRect(60, 890, 491, 161))
        self.ip_investing_opportunities_table.setMaximumSize(QtCore.QSize(641, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ip_investing_opportunities_table.setFont(font)
        self.ip_investing_opportunities_table.setAlternatingRowColors(False)
        self.ip_investing_opportunities_table.setObjectName("ip_investing_opportunities_table")
        self.ip_investing_opportunities_table.setColumnCount(4)
        self.ip_investing_opportunities_table.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ip_investing_opportunities_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ip_investing_opportunities_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ip_investing_opportunities_table.setHorizontalHeaderItem(3, item)
        self.ip_investing_opportunities_table.horizontalHeader().setDefaultSectionSize(110)
        self.ip_investing_opportunities_table.horizontalHeader().setStretchLastSection(True)
        self.ip_max_lineedit = QtWidgets.QLineEdit(self.ip_page)
        self.ip_max_lineedit.setGeometry(QtCore.QRect(450, 230, 113, 20))
        self.ip_max_lineedit.setObjectName("ip_max_lineedit")
        self.ip_interest_dash_label = QtWidgets.QLabel(self.ip_page)
        self.ip_interest_dash_label.setGeometry(QtCore.QRect(110, 260, 16, 16))
        self.ip_interest_dash_label.setObjectName("ip_interest_dash_label")
        self.ip_interest_label = QtWidgets.QLabel(self.ip_page)
        self.ip_interest_label.setGeometry(QtCore.QRect(60, 240, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ip_interest_label.setFont(font)
        self.ip_interest_label.setObjectName("ip_interest_label")
        self.ip_amount_invested_label = QtWidgets.QLabel(self.ip_page)
        self.ip_amount_invested_label.setGeometry(QtCore.QRect(450, 210, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ip_amount_invested_label.setFont(font)
        self.ip_amount_invested_label.setObjectName("ip_amount_invested_label")
        self.ip_duration1_lineedit = QtWidgets.QLineEdit(self.ip_page)
        self.ip_duration1_lineedit.setGeometry(QtCore.QRect(260, 260, 41, 20))
        self.ip_duration1_lineedit.setObjectName("ip_duration1_lineedit")
        self.ip_duration_dash_label = QtWidgets.QLabel(self.ip_page)
        self.ip_duration_dash_label.setGeometry(QtCore.QRect(310, 260, 16, 16))
        self.ip_duration_dash_label.setObjectName("ip_duration_dash_label")
        self.ip_duration_label = QtWidgets.QLabel(self.ip_page)
        self.ip_duration_label.setGeometry(QtCore.QRect(260, 240, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ip_duration_label.setFont(font)
        self.ip_duration_label.setObjectName("ip_duration_label")
        self.ip_duration2_lineedit = QtWidgets.QLineEdit(self.ip_page)
        self.ip_duration2_lineedit.setGeometry(QtCore.QRect(320, 260, 41, 20))
        self.ip_duration2_lineedit.setObjectName("ip_duration2_lineedit")
        self.ip_search_lineedit = QtWidgets.QLineEdit(self.ip_page)
        self.ip_search_lineedit.setGeometry(QtCore.QRect(60, 200, 141, 21))
        self.ip_search_lineedit.setObjectName("ip_search_lineedit")
        self.ip_accept_pushbutton = QtWidgets.QPushButton(self.ip_page)
        self.ip_accept_pushbutton.setEnabled(False)
        self.ip_accept_pushbutton.setGeometry(QtCore.QRect(480, 1060, 75, 23))
        self.ip_accept_pushbutton.setObjectName("ip_accept_pushbutton")
        self.ip_min_amount_lineedit = QtWidgets.QLineEdit(self.ip_page)
        self.ip_min_amount_lineedit.setGeometry(QtCore.QRect(450, 260, 113, 20))
        self.ip_min_amount_lineedit.setObjectName("ip_min_amount_lineedit")
        self.ip_investing_opportunities_label = QtWidgets.QLabel(self.ip_page)
        self.ip_investing_opportunities_label.setEnabled(False)
        self.ip_investing_opportunities_label.setGeometry(QtCore.QRect(60, 860, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ip_investing_opportunities_label.setFont(font)
        self.ip_investing_opportunities_label.setObjectName("ip_investing_opportunities_label")
        self.ip_search_pushbutton = QtWidgets.QPushButton(self.ip_page)
        self.ip_search_pushbutton.setGeometry(QtCore.QRect(220, 200, 75, 23))
        self.ip_search_pushbutton.setObjectName("ip_search_pushbutton")
        self.ip_sorting_options_label = QtWidgets.QLabel(self.ip_page)
        self.ip_sorting_options_label.setGeometry(QtCore.QRect(60, 170, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ip_sorting_options_label.setFont(font)
        self.ip_sorting_options_label.setObjectName("ip_sorting_options_label")
        self.ip_interest2_lineedit = QtWidgets.QLineEdit(self.ip_page)
        self.ip_interest2_lineedit.setGeometry(QtCore.QRect(120, 260, 41, 20))
        self.ip_interest2_lineedit.setObjectName("ip_interest2_lineedit")
        self.stackedWidget.addWidget(self.ip_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bplr_title_label.setText(_translate("MainWindow", "Place Loan Request"))
        self.bplr_housenumber_lineedit.setText(_translate("MainWindow", "123"))
        self.bplr_house_price_lineedit.setText(_translate("MainWindow", "120000"))
        self.bplr_postcode_label.setText(_translate("MainWindow", "Post Code"))
        self.bplr_postcode_lineedit.setText(_translate("MainWindow", "2625 BN"))
        self.bplr_seller_phone_number_lineedit.setText(_translate("MainWindow", "0612345678"))
        self.bplr_submit_button.setText(_translate("MainWindow", "Submit Loan Request"))
        self.bplr_mortgage_information_label.setText(_translate("MainWindow", "Mortgage Information"))
        self.bplr_amount_wanted_lineedit.setText(_translate("MainWindow", "80000"))
        self.bplr_housenumber_label.setText(_translate("MainWindow", "House Number"))
        self.bplr_mortgage_type_label.setText(_translate("MainWindow", "Mortgage Type"))
        self.bplr_house_price_label.setText(_translate("MainWindow", "House Price (€)"))
        self.bplr_preferred_banks_label.setText(_translate("MainWindow", "Preferred Banks"))
        self.bplr_seller_phone_number_label.setText(_translate("MainWindow", "Phone Number"))
        self.bplr_amount_wanted_label.setText(_translate("MainWindow", "Amount Wanted (€)"))
        self.bplr_linear_radiobutton.setText(_translate("MainWindow", "Linear"))
        self.bplr_fixedrate_radiobutton.setText(_translate("MainWindow", "Fixed-Rate"))
        self.bplr_house_link_label.setText(_translate("MainWindow", "Link to House [optional]"))
        self.bplr_property_information_label.setText(_translate("MainWindow", "Property Information"))
        self.bplr_description_label.setText(_translate("MainWindow", "Describe here why you want a loan for this house [optional]"))
        self.bplr_personal_information_label.setText(_translate("MainWindow", "Personal Information"))
        self.bplr_bank2_checkbox.setText(_translate("MainWindow", "Bank 2"))
        self.bplr_bank1_checkbox.setText(_translate("MainWindow", "Bank 1"))
        self.bplr_bank3_checkbox.setText(_translate("MainWindow", "Bank 3"))
        self.bplr_bank4_checkbox.setText(_translate("MainWindow", "Bank 4"))
        self.bplr_property_seller_information_label.setText(_translate("MainWindow", "Property Seller Information"))
        self.bplr_seller_email_label.setText(_translate("MainWindow", "Email address [optional]"))
        self.bplr_seller_email_lineedit.setText(_translate("MainWindow", "nigerian_prince_419@gmail.com"))
        self.prev_1.setText(_translate("MainWindow", "<"))
        self.next_1.setText(_translate("MainWindow", ">"))
        self.next_2.setText(_translate("MainWindow", ">"))
        self.fiplr1_pending_loan_requests_label.setText(_translate("MainWindow", "Pending Loan Requests"))
        self.fiplr1_loan_requests_table.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        item = self.fiplr1_loan_requests_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property Address"))
        item = self.fiplr1_loan_requests_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mortgage Type"))
        item = self.fiplr1_loan_requests_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Loan Amount"))
        item = self.fiplr1_loan_requests_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "House Price"))
        __sortingEnabled = self.fiplr1_loan_requests_table.isSortingEnabled()
        self.fiplr1_loan_requests_table.setSortingEnabled(False)
        self.fiplr1_loan_requests_table.setSortingEnabled(__sortingEnabled)
        self.fiplr1_view_loan_request_pushbutton.setText(_translate("MainWindow", "View loan request"))
        self.prev_2.setText(_translate("MainWindow", "<"))
        self.next_3.setText(_translate("MainWindow", ">"))
        self.prev_3.setText(_translate("MainWindow", "<"))
        self.fiplr2_property_address_label.setText(_translate("MainWindow", "Property Address"))
        self.fiplr2_lastname_label.setText(_translate("MainWindow", "Last Name"))
        self.fiplr2_loan_amount_label.setText(_translate("MainWindow", "Requested Loan Amount"))
        self.fiplr2_reject_pushbutton.setText(_translate("MainWindow", "Reject"))
        self.fiplr2_mortgage_information_label.setText(_translate("MainWindow", "Mortgage Request Information"))
        self.fiplr2_email_label.setText(_translate("MainWindow", "Email Address"))
        self.fiplr2_title_label.setText(_translate("MainWindow", "Pending Loan Requests"))
        self.fiplr2_phonenumber_label.setText(_translate("MainWindow", "Telephone Number"))
        self.fiplr2_loan_request_label.setText(_translate("MainWindow", "Loan Request"))
        self.fiplr2_loan_duration_label.setText(_translate("MainWindow", "Loan Duration (months)"))
        self.fiplr2_firstname_label.setText(_translate("MainWindow", "First Name"))
        self.fiplr2_address_label.setText(_translate("MainWindow", "Address"))
        self.fiplr2_offer_amount_label.setText(_translate("MainWindow", "Loan Amount Offered (€)"))
        self.fiplr2_personal_information_label.setText(_translate("MainWindow", "Personal Information"))
        self.fiplr2_risk_label.setText(_translate("MainWindow", "Current Risk Rating"))
        self.fiplr2_documents_label.setText(_translate("MainWindow", "Documents"))
        self.fiplr2_make_offer_label.setText(_translate("MainWindow", "Make Offer"))
        self.fiplr2_default_rate_label.setText(_translate("MainWindow", "Default Rate"))
        self.fiplr2_property_value_label.setText(_translate("MainWindow", "Property Value"))
        self.fiplr2_accept_pushbutton.setText(_translate("MainWindow", "Accept"))
        self.fiplr2_offer_interest_label.setText(_translate("MainWindow", "Interest (%)"))
        self.fiplr2_mortgage_type_label.setText(_translate("MainWindow", "Mortgage Type"))
        self.fiplr2_description_label.setText(_translate("MainWindow", "Description"))
        self.openmarket_view_loan_bids_pushbutton.setText(_translate("MainWindow", "View loan bids"))
        self.openmarket_duration_label.setText(_translate("MainWindow", "Duration (month)"))
        self.next_4.setText(_translate("MainWindow", ">"))
        self.openmarket_min_amount_lineedit.setText(_translate("MainWindow", "Min"))
        self.openmarket_rating_checkbox_b.setText(_translate("MainWindow", "B"))
        self.openmarket_interest_label.setText(_translate("MainWindow", "Interest (%)"))
        self.openmarket_search_lineedit.setText(_translate("MainWindow", "Type to search..."))
        self.openmarket_max_amount_lineedit.setText(_translate("MainWindow", "Max"))
        self.openmarket_interest1_lineedit.setText(_translate("MainWindow", "0"))
        self.openmarket_duration2_lineedit.setText(_translate("MainWindow", "36"))
        self.openmarket_interest_dash_label.setText(_translate("MainWindow", "-"))
        self.openmarket_rating_checkbox_c.setText(_translate("MainWindow", "C"))
        self.openmarket_duration_dash_label.setText(_translate("MainWindow", "-"))
        self.openmarket_search_pushbutton.setText(_translate("MainWindow", "Search"))
        self.prev_4.setText(_translate("MainWindow", "<"))
        self.openmarket_rating_label.setText(_translate("MainWindow", "Rating"))
        self.openmarket_sorting_options_label.setText(_translate("MainWindow", "Sorting Options"))
        self.openmarket_title_label.setText(_translate("MainWindow", "Open Market"))
        self.openmarket_rating_checkbox_a.setText(_translate("MainWindow", "A"))
        self.openmarket_amount_label.setText(_translate("MainWindow", "Amount (€)"))
        self.openmarket_duration1_lineedit.setText(_translate("MainWindow", "12"))
        self.openmarket_interest2_lineedit.setText(_translate("MainWindow", "100"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property Address"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount (€)"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Interest (%)"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Duration (month)"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Risk"))
        __sortingEnabled = self.openmarket_open_market_table.isSortingEnabled()
        self.openmarket_open_market_table.setSortingEnabled(False)
        item = self.openmarket_open_market_table.item(0, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.openmarket_open_market_table.item(0, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.openmarket_open_market_table.item(0, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.openmarket_open_market_table.item(0, 3)
        item.setText(_translate("MainWindow", " "))
        item = self.openmarket_open_market_table.item(0, 4)
        item.setText(_translate("MainWindow", " "))
        item = self.openmarket_open_market_table.item(1, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.openmarket_open_market_table.item(1, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.openmarket_open_market_table.item(1, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.openmarket_open_market_table.item(1, 3)
        item.setText(_translate("MainWindow", " "))
        item = self.openmarket_open_market_table.item(1, 4)
        item.setText(_translate("MainWindow", " "))
        self.openmarket_open_market_table.setSortingEnabled(__sortingEnabled)
        self.icb_duration_label.setText(_translate("MainWindow", "Duration (months)"))
        item = self.icb_current_bids_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Amount (€)"))
        item = self.icb_current_bids_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Duration (month)"))
        item = self.icb_current_bids_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Interest (%)"))
        __sortingEnabled = self.icb_current_bids_table.isSortingEnabled()
        self.icb_current_bids_table.setSortingEnabled(False)
        item = self.icb_current_bids_table.item(0, 0)
        item.setText(_translate("MainWindow", "  "))
        item = self.icb_current_bids_table.item(0, 1)
        item.setText(_translate("MainWindow", "  "))
        item = self.icb_current_bids_table.item(0, 2)
        item.setText(_translate("MainWindow", "  "))
        self.icb_current_bids_table.setSortingEnabled(__sortingEnabled)
        self.icb_place_bid_label.setText(_translate("MainWindow", "Place Bid"))
        self.icb_amount_label.setText(_translate("MainWindow", "Amount Offered (€)"))
        self.icb_place_bid_pushbutton.setText(_translate("MainWindow", "Place Bid"))
        self.icb_current_bids_label.setText(_translate("MainWindow", "Current Bids"))
        self.icb_interest_label.setText(_translate("MainWindow", "Interest Rate (%)"))
        self.icb_title_label.setText(_translate("MainWindow", "Campaign Bids"))
        self.icb_property_address_label.setText(_translate("MainWindow", "Property Address"))
        self.prev_5.setText(_translate("MainWindow", "<"))
        self.next_5.setText(_translate("MainWindow", ">"))
        self.next_6.setText(_translate("MainWindow", ">"))
        self.ip_reject_pushbutton.setText(_translate("MainWindow", "Reject"))
        self.ip_interest1_lineedit.setText(_translate("MainWindow", "0"))
        self.ip_ongoing_investments_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Overview ongoing investments</span></p></body></html>"))
        self.ip_investors_portfolio_label.setText(_translate("MainWindow", "Investor\'s Portfolio"))
        self.prev_6.setText(_translate("MainWindow", "<"))
        self.ip_investments_table.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.ip_investments_table.setSortingEnabled(True)
        item = self.ip_investments_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property Address"))
        item = self.ip_investments_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Campaign Status"))
        item = self.ip_investments_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Investment Status"))
        item = self.ip_investments_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Amount Invested (€)"))
        item = self.ip_investments_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Interest (%)"))
        item = self.ip_investments_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Duration (month)"))
        __sortingEnabled = self.ip_investments_table.isSortingEnabled()
        self.ip_investments_table.setSortingEnabled(False)
        self.ip_investments_table.setSortingEnabled(__sortingEnabled)
        item = self.ip_investing_opportunities_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property Address"))
        item = self.ip_investing_opportunities_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount Invested (€)"))
        item = self.ip_investing_opportunities_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", " (%)"))
        item = self.ip_investing_opportunities_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Duration (month)"))
        self.ip_max_lineedit.setText(_translate("MainWindow", "Max"))
        self.ip_interest_dash_label.setText(_translate("MainWindow", "-"))
        self.ip_interest_label.setText(_translate("MainWindow", "Interest (%)"))
        self.ip_amount_invested_label.setText(_translate("MainWindow", "Amount invested (€)"))
        self.ip_duration1_lineedit.setText(_translate("MainWindow", "12"))
        self.ip_duration_dash_label.setText(_translate("MainWindow", "-"))
        self.ip_duration_label.setText(_translate("MainWindow", "Duration (month)"))
        self.ip_duration2_lineedit.setText(_translate("MainWindow", "36"))
        self.ip_search_lineedit.setText(_translate("MainWindow", "Type to search..."))
        self.ip_accept_pushbutton.setText(_translate("MainWindow", "Accept"))
        self.ip_min_amount_lineedit.setText(_translate("MainWindow", "Min"))
        self.ip_investing_opportunities_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Investing opportunities</span></p></body></html>"))
        self.ip_search_pushbutton.setText(_translate("MainWindow", "Search"))
        self.ip_sorting_options_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Sorting Options</span></p></body></html>"))
        self.ip_interest2_lineedit.setText(_translate("MainWindow", "100"))

