# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/main_screenRE7977.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(693, 622)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.generateLabel = QtWidgets.QLabel(self.page)
        self.generateLabel.setGeometry(QtCore.QRect(40, 330, 651, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generateLabel.setFont(font)
        self.generateLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.generateLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.generateLabel.setObjectName("generateLabel")
        self.titleLabel = QtWidgets.QLabel(self.page)
        self.titleLabel.setGeometry(QtCore.QRect(10, 190, 651, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.titleLabel.setFont(font)
        self.titleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.keyFieldLabel = QtWidgets.QLabel(self.page)
        self.keyFieldLabel.setGeometry(QtCore.QRect(40, 240, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.keyFieldLabel.setFont(font)
        self.keyFieldLabel.setObjectName("keyFieldLabel")
        self.loginButton = QtWidgets.QPushButton(self.page)
        self.loginButton.setGeometry(QtCore.QRect(440, 290, 80, 23))
        self.loginButton.setObjectName("loginButton")
        self.rememberMeCheckBox = QtWidgets.QCheckBox(self.page)
        self.rememberMeCheckBox.setEnabled(True)
        self.rememberMeCheckBox.setGeometry(QtCore.QRect(314, 290, 111, 21))
        self.rememberMeCheckBox.setAutoFillBackground(False)
        self.rememberMeCheckBox.setChecked(True)
        self.rememberMeCheckBox.setTristate(False)
        self.rememberMeCheckBox.setObjectName("rememberMeCheckBox")
        self.generateButton = QtWidgets.QPushButton(self.page)
        self.generateButton.setGeometry(QtCore.QRect(40, 370, 80, 23))
        self.generateButton.setObjectName("generateButton")
        self.keyField = QtWidgets.QLineEdit(self.page)
        self.keyField.setGeometry(QtCore.QRect(40, 260, 481, 23))
        self.keyField.setObjectName("keyField")
        self.browseButton = QtWidgets.QToolButton(self.page)
        self.browseButton.setGeometry(QtCore.QRect(540, 260, 71, 22))
        self.browseButton.setObjectName("browseButton")
        StackedWidget.addWidget(self.page)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.label_6 = QtWidgets.QLabel(self.page1)
        self.label_6.setGeometry(QtCore.QRect(300, 150, 171, 17))
        self.label_6.setObjectName("label_6")
        self.lastNameField = QtWidgets.QLineEdit(self.page1)
        self.lastNameField.setGeometry(QtCore.QRect(300, 110, 191, 27))
        self.lastNameField.setObjectName("lastNameField")
        self.firstNameField = QtWidgets.QLineEdit(self.page1)
        self.firstNameField.setGeometry(QtCore.QRect(90, 110, 191, 27))
        self.firstNameField.setObjectName("firstNameField")
        self.label_4 = QtWidgets.QLabel(self.page1)
        self.label_4.setGeometry(QtCore.QRect(300, 90, 211, 17))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.page1)
        self.label_10.setGeometry(QtCore.QRect(90, 390, 181, 17))
        self.label_10.setObjectName("label_10")
        self.titleLabel_2 = QtWidgets.QLabel(self.page1)
        self.titleLabel_2.setGeometry(QtCore.QRect(80, 30, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel_2.setFont(font)
        self.titleLabel_2.setObjectName("titleLabel_2")
        self.curAddressField = QtWidgets.QLineEdit(self.page1)
        self.curAddressField.setEnabled(False)
        self.curAddressField.setGeometry(QtCore.QRect(90, 230, 401, 31))
        self.curAddressField.setObjectName("curAddressField")
        self.IBANField = QtWidgets.QLineEdit(self.page1)
        self.IBANField.setGeometry(QtCore.QRect(90, 350, 401, 27))
        self.IBANField.setObjectName("IBANField")
        self.telNumberField = QtWidgets.QLineEdit(self.page1)
        self.telNumberField.setEnabled(True)
        self.telNumberField.setGeometry(QtCore.QRect(300, 290, 191, 27))
        self.telNumberField.setObjectName("telNumberField")
        self.label_7 = QtWidgets.QLabel(self.page1)
        self.label_7.setGeometry(QtCore.QRect(90, 210, 141, 17))
        self.label_7.setObjectName("label_7")
        self.curHouseNumberField = QtWidgets.QLineEdit(self.page1)
        self.curHouseNumberField.setEnabled(False)
        self.curHouseNumberField.setGeometry(QtCore.QRect(300, 170, 191, 27))
        self.curHouseNumberField.setObjectName("curHouseNumberField")
        self.saveButton = QtWidgets.QPushButton(self.page1)
        self.saveButton.setGeometry(QtCore.QRect(500, 540, 121, 27))
        self.saveButton.setObjectName("saveButton")
        self.curPostalCodeField = QtWidgets.QLineEdit(self.page1)
        self.curPostalCodeField.setEnabled(False)
        self.curPostalCodeField.setGeometry(QtCore.QRect(90, 170, 191, 27))
        self.curPostalCodeField.setObjectName("curPostalCodeField")
        self.label_2 = QtWidgets.QLabel(self.page1)
        self.label_2.setGeometry(QtCore.QRect(90, 60, 57, 21))
        self.label_2.setObjectName("label_2")
        self.emailAddressField = QtWidgets.QLineEdit(self.page1)
        self.emailAddressField.setGeometry(QtCore.QRect(90, 290, 191, 27))
        self.emailAddressField.setObjectName("emailAddressField")
        self.label_5 = QtWidgets.QLabel(self.page1)
        self.label_5.setGeometry(QtCore.QRect(90, 150, 141, 17))
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.page1)
        self.label_9.setGeometry(QtCore.QRect(90, 270, 141, 17))
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.page1)
        self.label_3.setGeometry(QtCore.QRect(90, 90, 131, 17))
        self.label_3.setObjectName("label_3")
        self.radioButtonInvestor = QtWidgets.QRadioButton(self.page1)
        self.radioButtonInvestor.setGeometry(QtCore.QRect(250, 60, 104, 22))
        self.radioButtonInvestor.setChecked(True)
        self.radioButtonInvestor.setObjectName("radioButtonInvestor")
        self.label_11 = QtWidgets.QLabel(self.page1)
        self.label_11.setGeometry(QtCore.QRect(90, 330, 57, 17))
        self.label_11.setObjectName("label_11")
        self.documentsTable = QtWidgets.QTableWidget(self.page1)
        self.documentsTable.setEnabled(False)
        self.documentsTable.setGeometry(QtCore.QRect(90, 410, 541, 101))
        self.documentsTable.setObjectName("documentsTable")
        self.documentsTable.setColumnCount(0)
        self.documentsTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(4, item)
        self.radioButtonBorrower = QtWidgets.QRadioButton(self.page1)
        self.radioButtonBorrower.setGeometry(QtCore.QRect(140, 60, 104, 22))
        self.radioButtonBorrower.setObjectName("radioButtonBorrower")
        self.label_8 = QtWidgets.QLabel(self.page1)
        self.label_8.setGeometry(QtCore.QRect(300, 270, 141, 17))
        self.label_8.setObjectName("label_8")
        StackedWidget.addWidget(self.page1)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.generateLabel.setText(_translate("StackedWidget", "Don\'t have a private key?"))
        self.titleLabel.setText(_translate("StackedWidget", "Login"))
        self.keyFieldLabel.setText(_translate("StackedWidget", "Private key"))
        self.loginButton.setText(_translate("StackedWidget", "Login"))
        self.rememberMeCheckBox.setText(_translate("StackedWidget", "Remember Me"))
        self.generateButton.setText(_translate("StackedWidget", "Generate "))
        self.browseButton.setToolTip(_translate("StackedWidget", "<html><head/><body><p><br/></p></body></html>"))
        self.browseButton.setText(_translate("StackedWidget", "Browse"))
        self.label_6.setText(_translate("StackedWidget", "Current House Number"))
        self.label_4.setText(_translate("StackedWidget", "Last Name"))
        self.label_10.setText(_translate("StackedWidget", "Documents"))
        self.titleLabel_2.setText(_translate("StackedWidget", "Profile"))
        self.label_7.setText(_translate("StackedWidget", "Current Address"))
        self.saveButton.setText(_translate("StackedWidget", "Save Changes"))
        self.label_2.setText(_translate("StackedWidget", "I am a:"))
        self.label_5.setText(_translate("StackedWidget", "Current Post Code"))
        self.label_9.setText(_translate("StackedWidget", "Email Address"))
        self.label_3.setText(_translate("StackedWidget", "First Name"))
        self.radioButtonInvestor.setText(_translate("StackedWidget", "Investor"))
        self.label_11.setText(_translate("StackedWidget", "IBAN"))
        item = self.documentsTable.verticalHeaderItem(0)
        item.setText(_translate("StackedWidget", "Example Document 1"))
        item = self.documentsTable.verticalHeaderItem(1)
        item.setText(_translate("StackedWidget", "Example Document 2"))
        item = self.documentsTable.verticalHeaderItem(2)
        item.setText(_translate("StackedWidget", "Example Document 3"))
        item = self.documentsTable.verticalHeaderItem(3)
        item.setText(_translate("StackedWidget", "Example Document 4"))
        item = self.documentsTable.verticalHeaderItem(4)
        item.setText(_translate("StackedWidget", "Example Document 5"))
        self.radioButtonBorrower.setText(_translate("StackedWidget", "Borrower"))
        self.label_8.setText(_translate("StackedWidget", "Telephone Number"))

