# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/mainwindowjk6521.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(855, 655)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.login_title = QtWidgets.QLabel(self.login_page)
        self.login_title.setGeometry(QtCore.QRect(360, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.login_title.setFont(font)
        self.login_title.setObjectName("login_title")
        self.login_browse_button = QtWidgets.QToolButton(self.login_page)
        self.login_browse_button.setGeometry(QtCore.QRect(650, 310, 71, 22))
        self.login_browse_button.setObjectName("login_browse_button")
        self.login_remember_me_checkbox = QtWidgets.QCheckBox(self.login_page)
        self.login_remember_me_checkbox.setGeometry(QtCore.QRect(394, 340, 111, 21))
        self.login_remember_me_checkbox.setChecked(True)
        self.login_remember_me_checkbox.setObjectName("login_remember_me_checkbox")
        self.login_private_key_label = QtWidgets.QLabel(self.login_page)
        self.login_private_key_label.setGeometry(QtCore.QRect(120, 280, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_private_key_label.setFont(font)
        self.login_private_key_label.setObjectName("login_private_key_label")
        self.login_generate_button = QtWidgets.QPushButton(self.login_page)
        self.login_generate_button.setGeometry(QtCore.QRect(120, 460, 80, 23))
        self.login_generate_button.setObjectName("login_generate_button")
        self.login_private_key_line = QtWidgets.QLineEdit(self.login_page)
        self.login_private_key_line.setGeometry(QtCore.QRect(120, 310, 481, 23))
        self.login_private_key_line.setObjectName("login_private_key_line")
        self.login_push_button = QtWidgets.QPushButton(self.login_page)
        self.login_push_button.setGeometry(QtCore.QRect(520, 340, 80, 23))
        self.login_push_button.setObjectName("login_push_button")
        self.login_no_private_key_label = QtWidgets.QLabel(self.login_page)
        self.login_no_private_key_label.setGeometry(QtCore.QRect(120, 430, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_no_private_key_label.setFont(font)
        self.login_no_private_key_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login_no_private_key_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.login_no_private_key_label.setObjectName("login_no_private_key_label")
        self.prev_1 = QtWidgets.QToolButton(self.login_page)
        self.prev_1.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_1.setObjectName("prev_1")
        self.next_1 = QtWidgets.QToolButton(self.login_page)
        self.next_1.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_1.setObjectName("next_1")
        StackedWidget.addWidget(self.login_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.profile_email_label = QtWidgets.QLabel(self.profile_page)
        self.profile_email_label.setGeometry(QtCore.QRect(60, 300, 141, 17))
        self.profile_email_label.setObjectName("profile_email_label")
        self.profile_firstname_label = QtWidgets.QLabel(self.profile_page)
        self.profile_firstname_label.setGeometry(QtCore.QRect(60, 120, 131, 17))
        self.profile_firstname_label.setObjectName("profile_firstname_label")
        self.profile_iban_lineedit = QtWidgets.QLineEdit(self.profile_page)
        self.profile_iban_lineedit.setGeometry(QtCore.QRect(60, 380, 401, 27))
        self.profile_iban_lineedit.setObjectName("profile_iban_lineedit")
        self.profile_housenumber_label = QtWidgets.QLabel(self.profile_page)
        self.profile_housenumber_label.setGeometry(QtCore.QRect(270, 180, 171, 17))
        self.profile_housenumber_label.setObjectName("profile_housenumber_label")
        self.profile_address_label = QtWidgets.QLabel(self.profile_page)
        self.profile_address_label.setGeometry(QtCore.QRect(60, 240, 141, 17))
        self.profile_address_label.setObjectName("profile_address_label")
        self.profile_phonenumber_lineedit = QtWidgets.QLineEdit(self.profile_page)
        self.profile_phonenumber_lineedit.setEnabled(True)
        self.profile_phonenumber_lineedit.setGeometry(QtCore.QRect(270, 320, 191, 27))
        self.profile_phonenumber_lineedit.setObjectName("profile_phonenumber_lineedit")
        self.profile_address_lineedit = QtWidgets.QLineEdit(self.profile_page)
        self.profile_address_lineedit.setEnabled(False)
        self.profile_address_lineedit.setGeometry(QtCore.QRect(60, 260, 401, 31))
        self.profile_address_lineedit.setObjectName("profile_address_lineedit")
        self.role_label = QtWidgets.QLabel(self.profile_page)
        self.role_label.setGeometry(QtCore.QRect(60, 90, 57, 21))
        self.role_label.setObjectName("role_label")
        self.profile_postcode_label = QtWidgets.QLabel(self.profile_page)
        self.profile_postcode_label.setGeometry(QtCore.QRect(60, 180, 141, 17))
        self.profile_postcode_label.setObjectName("profile_postcode_label")
        self.profile_lastname_label = QtWidgets.QLabel(self.profile_page)
        self.profile_lastname_label.setGeometry(QtCore.QRect(270, 120, 211, 17))
        self.profile_lastname_label.setObjectName("profile_lastname_label")
        self.profile_title = QtWidgets.QLabel(self.profile_page)
        self.profile_title.setGeometry(QtCore.QRect(60, 60, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.profile_title.setFont(font)
        self.profile_title.setObjectName("profile_title")
        self.profile_postcode_lineedit = QtWidgets.QLineEdit(self.profile_page)
        self.profile_postcode_lineedit.setGeometry(QtCore.QRect(60, 200, 191, 27))
        self.profile_postcode_lineedit.setObjectName("profile_postcode_lineedit")
        self.profile_borrower_radiobutton = QtWidgets.QRadioButton(self.profile_page)
        self.profile_borrower_radiobutton.setGeometry(QtCore.QRect(110, 90, 104, 22))
        self.profile_borrower_radiobutton.setChecked(True)
        self.profile_borrower_radiobutton.setObjectName("profile_borrower_radiobutton")
        self.profile_housenumber_lineedit = QtWidgets.QLineEdit(self.profile_page)
        self.profile_housenumber_lineedit.setGeometry(QtCore.QRect(270, 200, 191, 27))
        self.profile_housenumber_lineedit.setObjectName("profile_housenumber_lineedit")
        self.profile_phonenumber_label = QtWidgets.QLabel(self.profile_page)
        self.profile_phonenumber_label.setGeometry(QtCore.QRect(270, 300, 141, 17))
        self.profile_phonenumber_label.setObjectName("profile_phonenumber_label")
        self.profile_iban_label = QtWidgets.QLabel(self.profile_page)
        self.profile_iban_label.setGeometry(QtCore.QRect(60, 360, 57, 17))
        self.profile_iban_label.setObjectName("profile_iban_label")
        self.profile_email_lineedit = QtWidgets.QLineEdit(self.profile_page)
        self.profile_email_lineedit.setGeometry(QtCore.QRect(60, 320, 191, 27))
        self.profile_email_lineedit.setObjectName("profile_email_lineedit")
        self.profile_lastname_lineedit = QtWidgets.QLineEdit(self.profile_page)
        self.profile_lastname_lineedit.setGeometry(QtCore.QRect(270, 140, 191, 27))
        self.profile_lastname_lineedit.setObjectName("profile_lastname_lineedit")
        self.profile_documents_label = QtWidgets.QLabel(self.profile_page)
        self.profile_documents_label.setGeometry(QtCore.QRect(60, 420, 181, 17))
        self.profile_documents_label.setObjectName("profile_documents_label")
        self.profile_investor_radiobutton = QtWidgets.QRadioButton(self.profile_page)
        self.profile_investor_radiobutton.setGeometry(QtCore.QRect(220, 90, 104, 22))
        self.profile_investor_radiobutton.setChecked(False)
        self.profile_investor_radiobutton.setObjectName("profile_investor_radiobutton")
        self.profile_documents_table = QtWidgets.QTableWidget(self.profile_page)
        self.profile_documents_table.setGeometry(QtCore.QRect(60, 440, 541, 101))
        self.profile_documents_table.setObjectName("profile_documents_table")
        self.profile_documents_table.setColumnCount(0)
        self.profile_documents_table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.profile_documents_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.profile_documents_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.profile_documents_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.profile_documents_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.profile_documents_table.setVerticalHeaderItem(4, item)
        self.profile_firstname_lineedit = QtWidgets.QLineEdit(self.profile_page)
        self.profile_firstname_lineedit.setGeometry(QtCore.QRect(60, 140, 191, 27))
        self.profile_firstname_lineedit.setObjectName("profile_firstname_lineedit")
        self.profile_save_button = QtWidgets.QPushButton(self.profile_page)
        self.profile_save_button.setGeometry(QtCore.QRect(470, 570, 121, 27))
        self.profile_save_button.setObjectName("profile_save_button")
        self.next_2 = QtWidgets.QToolButton(self.profile_page)
        self.next_2.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_2.setObjectName("next_2")
        self.prev_2 = QtWidgets.QToolButton(self.profile_page)
        self.prev_2.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_2.setObjectName("prev_2")
        StackedWidget.addWidget(self.profile_page)
        self.place_loan_request = QtWidgets.QWidget()
        self.place_loan_request.setObjectName("place_loan_request")
        self.gridLayoutWidget = QtWidgets.QWidget(self.place_loan_request)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 50, 611, 589))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bplr_title_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_title_label.setFont(font)
        self.bplr_title_label.setObjectName("bplr_title_label")
        self.gridLayout.addWidget(self.bplr_title_label, 0, 0, 1, 1)
        self.bplr_housenumber_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_housenumber_lineedit.setObjectName("bplr_housenumber_lineedit")
        self.gridLayout.addWidget(self.bplr_housenumber_lineedit, 3, 1, 1, 1)
        self.bplr_house_price_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_house_price_lineedit.setObjectName("bplr_house_price_lineedit")
        self.gridLayout.addWidget(self.bplr_house_price_lineedit, 5, 0, 1, 1)
        self.bplr_postcode_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_postcode_label.setFont(font)
        self.bplr_postcode_label.setObjectName("bplr_postcode_label")
        self.gridLayout.addWidget(self.bplr_postcode_label, 2, 0, 1, 1)
        self.bplr_postcode_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_postcode_lineedit.setObjectName("bplr_postcode_lineedit")
        self.gridLayout.addWidget(self.bplr_postcode_lineedit, 3, 0, 1, 1)
        self.bplr_seller_phone_number_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_seller_phone_number_lineedit.setObjectName("bplr_seller_phone_number_lineedit")
        self.gridLayout.addWidget(self.bplr_seller_phone_number_lineedit, 8, 0, 1, 1)
        self.bplr_house_link_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_house_link_lineedit.setObjectName("bplr_house_link_lineedit")
        self.gridLayout.addWidget(self.bplr_house_link_lineedit, 5, 1, 1, 1)
        self.bplr_submit_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bplr_submit_button.setObjectName("bplr_submit_button")
        self.gridLayout.addWidget(self.bplr_submit_button, 18, 1, 1, 1)
        self.bplr_mortgage_information_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_mortgage_information_label.setFont(font)
        self.bplr_mortgage_information_label.setObjectName("bplr_mortgage_information_label")
        self.gridLayout.addWidget(self.bplr_mortgage_information_label, 9, 0, 1, 1)
        self.bplr_amount_wanted_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_amount_wanted_lineedit.setObjectName("bplr_amount_wanted_lineedit")
        self.gridLayout.addWidget(self.bplr_amount_wanted_lineedit, 11, 0, 1, 1)
        self.bplr_housenumber_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_housenumber_label.setFont(font)
        self.bplr_housenumber_label.setObjectName("bplr_housenumber_label")
        self.gridLayout.addWidget(self.bplr_housenumber_label, 2, 1, 1, 1)
        self.bplr_mortgage_type_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_mortgage_type_label.setFont(font)
        self.bplr_mortgage_type_label.setObjectName("bplr_mortgage_type_label")
        self.gridLayout.addWidget(self.bplr_mortgage_type_label, 10, 1, 1, 1)
        self.bplr_house_price_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_house_price_label.setFont(font)
        self.bplr_house_price_label.setObjectName("bplr_house_price_label")
        self.gridLayout.addWidget(self.bplr_house_price_label, 4, 0, 1, 1)
        self.bplr_preferred_banks_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bplr_preferred_banks_label.setObjectName("bplr_preferred_banks_label")
        self.gridLayout.addWidget(self.bplr_preferred_banks_label, 12, 0, 1, 1)
        self.bplr_seller_phone_number_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bplr_seller_phone_number_label.setObjectName("bplr_seller_phone_number_label")
        self.gridLayout.addWidget(self.bplr_seller_phone_number_label, 7, 0, 1, 1)
        self.bplr_amount_wanted_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_amount_wanted_label.setFont(font)
        self.bplr_amount_wanted_label.setObjectName("bplr_amount_wanted_label")
        self.gridLayout.addWidget(self.bplr_amount_wanted_label, 10, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bplr_linear_radiobutton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.bplr_linear_radiobutton.setObjectName("bplr_linear_radiobutton")
        self.gridLayout_2.addWidget(self.bplr_linear_radiobutton, 0, 0, 1, 1)
        self.bplr_fixedrate_radiobutton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.bplr_fixedrate_radiobutton.setObjectName("bplr_fixedrate_radiobutton")
        self.gridLayout_2.addWidget(self.bplr_fixedrate_radiobutton, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 11, 1, 1, 1)
        self.bplr_house_link_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bplr_house_link_label.setFont(font)
        self.bplr_house_link_label.setObjectName("bplr_house_link_label")
        self.gridLayout.addWidget(self.bplr_house_link_label, 4, 1, 1, 1)
        self.bplr_property_information_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_property_information_label.setFont(font)
        self.bplr_property_information_label.setObjectName("bplr_property_information_label")
        self.gridLayout.addWidget(self.bplr_property_information_label, 1, 0, 1, 1)
        self.bplr_description_textedit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.bplr_description_textedit.setObjectName("bplr_description_textedit")
        self.gridLayout.addWidget(self.bplr_description_textedit, 17, 0, 1, 2)
        self.bplr_description_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.bplr_description_label.setFont(font)
        self.bplr_description_label.setObjectName("bplr_description_label")
        self.gridLayout.addWidget(self.bplr_description_label, 16, 0, 1, 2)
        self.bplr_personal_information_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_personal_information_label.setFont(font)
        self.bplr_personal_information_label.setObjectName("bplr_personal_information_label")
        self.gridLayout.addWidget(self.bplr_personal_information_label, 15, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.bplr_bank2_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bplr_bank2_checkbox.setObjectName("bplr_bank2_checkbox")
        self.gridLayout_4.addWidget(self.bplr_bank2_checkbox, 0, 1, 1, 1)
        self.bplr_bank1_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bplr_bank1_checkbox.setObjectName("bplr_bank1_checkbox")
        self.gridLayout_4.addWidget(self.bplr_bank1_checkbox, 0, 0, 1, 1)
        self.bplr_bank3_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bplr_bank3_checkbox.setObjectName("bplr_bank3_checkbox")
        self.gridLayout_4.addWidget(self.bplr_bank3_checkbox, 1, 0, 1, 1)
        self.bplr_bank4_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.bplr_bank4_checkbox.setObjectName("bplr_bank4_checkbox")
        self.gridLayout_4.addWidget(self.bplr_bank4_checkbox, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 14, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout.addLayout(self.gridLayout_5, 14, 1, 1, 1)
        self.bplr_property_seller_information_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bplr_property_seller_information_label.setFont(font)
        self.bplr_property_seller_information_label.setObjectName("bplr_property_seller_information_label")
        self.gridLayout.addWidget(self.bplr_property_seller_information_label, 6, 0, 1, 1)
        self.bplr_seller_email_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bplr_seller_email_label.setObjectName("bplr_seller_email_label")
        self.gridLayout.addWidget(self.bplr_seller_email_label, 7, 1, 1, 1)
        self.bplr_seller_email_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bplr_seller_email_lineedit.setObjectName("bplr_seller_email_lineedit")
        self.gridLayout.addWidget(self.bplr_seller_email_lineedit, 8, 1, 1, 1)
        self.prev_3 = QtWidgets.QToolButton(self.place_loan_request)
        self.prev_3.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_3.setObjectName("prev_3")
        self.next_3 = QtWidgets.QToolButton(self.place_loan_request)
        self.next_3.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_3.setObjectName("next_3")
        StackedWidget.addWidget(self.place_loan_request)
        self.borrowers_portfolio = QtWidgets.QWidget()
        self.borrowers_portfolio.setObjectName("borrowers_portfolio")
        self.bp_open_offers_table = QtWidgets.QTableWidget(self.borrowers_portfolio)
        self.bp_open_offers_table.setGeometry(QtCore.QRect(60, 340, 601, 161))
        self.bp_open_offers_table.setMaximumSize(QtCore.QSize(641, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bp_open_offers_table.setFont(font)
        self.bp_open_offers_table.setAlternatingRowColors(False)
        self.bp_open_offers_table.setObjectName("bp_open_offers_table")
        self.bp_open_offers_table.setColumnCount(5)
        self.bp_open_offers_table.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_open_offers_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_open_offers_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_open_offers_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_open_offers_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_open_offers_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_open_offers_table.setHorizontalHeaderItem(4, item)
        self.bp_open_offers_table.horizontalHeader().setDefaultSectionSize(110)
        self.bp_open_offers_table.horizontalHeader().setStretchLastSection(True)
        self.bp_reject_pushbutton = QtWidgets.QPushButton(self.borrowers_portfolio)
        self.bp_reject_pushbutton.setGeometry(QtCore.QRect(510, 520, 75, 23))
        self.bp_reject_pushbutton.setObjectName("bp_reject_pushbutton")
        self.bp_open_offers_label = QtWidgets.QLabel(self.borrowers_portfolio)
        self.bp_open_offers_label.setGeometry(QtCore.QRect(60, 310, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bp_open_offers_label.setFont(font)
        self.bp_open_offers_label.setObjectName("bp_open_offers_label")
        self.bp_accept_pushbutton = QtWidgets.QPushButton(self.borrowers_portfolio)
        self.bp_accept_pushbutton.setGeometry(QtCore.QRect(590, 520, 75, 23))
        self.bp_accept_pushbutton.setObjectName("bp_accept_pushbutton")
        self.bp_ongoing_loans_label = QtWidgets.QLabel(self.borrowers_portfolio)
        self.bp_ongoing_loans_label.setGeometry(QtCore.QRect(60, 100, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bp_ongoing_loans_label.setFont(font)
        self.bp_ongoing_loans_label.setObjectName("bp_ongoing_loans_label")
        self.bp_title_label = QtWidgets.QLabel(self.borrowers_portfolio)
        self.bp_title_label.setGeometry(QtCore.QRect(60, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bp_title_label.setFont(font)
        self.bp_title_label.setObjectName("bp_title_label")
        self.bp_ongoing_loans_table = QtWidgets.QTableWidget(self.borrowers_portfolio)
        self.bp_ongoing_loans_table.setGeometry(QtCore.QRect(60, 130, 601, 161))
        self.bp_ongoing_loans_table.setMaximumSize(QtCore.QSize(641, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bp_ongoing_loans_table.setFont(font)
        self.bp_ongoing_loans_table.setAlternatingRowColors(False)
        self.bp_ongoing_loans_table.setObjectName("bp_ongoing_loans_table")
        self.bp_ongoing_loans_table.setColumnCount(5)
        self.bp_ongoing_loans_table.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.bp_ongoing_loans_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_ongoing_loans_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_ongoing_loans_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_ongoing_loans_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_ongoing_loans_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bp_ongoing_loans_table.setHorizontalHeaderItem(4, item)
        self.bp_ongoing_loans_table.horizontalHeader().setDefaultSectionSize(110)
        self.bp_ongoing_loans_table.horizontalHeader().setStretchLastSection(True)
        self.prev_4 = QtWidgets.QToolButton(self.borrowers_portfolio)
        self.prev_4.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_4.setObjectName("prev_4")
        self.next_4 = QtWidgets.QToolButton(self.borrowers_portfolio)
        self.next_4.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_4.setObjectName("next_4")
        StackedWidget.addWidget(self.borrowers_portfolio)
        self.pending_loan_request_page1 = QtWidgets.QWidget()
        self.pending_loan_request_page1.setObjectName("pending_loan_request_page1")
        self.fiplr1_pending_loan_requests_label = QtWidgets.QLabel(self.pending_loan_request_page1)
        self.fiplr1_pending_loan_requests_label.setGeometry(QtCore.QRect(60, 60, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr1_pending_loan_requests_label.setFont(font)
        self.fiplr1_pending_loan_requests_label.setObjectName("fiplr1_pending_loan_requests_label")
        self.fiplr1_pushbutton = QtWidgets.QPushButton(self.pending_loan_request_page1)
        self.fiplr1_pushbutton.setGeometry(QtCore.QRect(540, 360, 121, 27))
        self.fiplr1_pushbutton.setObjectName("fiplr1_pushbutton")
        self.fiplr1_loan_requests_table = QtWidgets.QTableWidget(self.pending_loan_request_page1)
        self.fiplr1_loan_requests_table.setEnabled(True)
        self.fiplr1_loan_requests_table.setGeometry(QtCore.QRect(60, 120, 571, 211))
        self.fiplr1_loan_requests_table.setMaximumSize(QtCore.QSize(571, 16777215))
        self.fiplr1_loan_requests_table.setObjectName("fiplr1_loan_requests_table")
        self.fiplr1_loan_requests_table.setColumnCount(4)
        self.fiplr1_loan_requests_table.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.fiplr1_loan_requests_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fiplr1_loan_requests_table.setHorizontalHeaderItem(3, item)
        self.fiplr1_loan_requests_table.horizontalHeader().setDefaultSectionSize(138)
        self.fiplr1_loan_requests_table.verticalHeader().setDefaultSectionSize(30)
        self.prev_5 = QtWidgets.QToolButton(self.pending_loan_request_page1)
        self.prev_5.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_5.setObjectName("prev_5")
        self.next_5 = QtWidgets.QToolButton(self.pending_loan_request_page1)
        self.next_5.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_5.setObjectName("next_5")
        StackedWidget.addWidget(self.pending_loan_request_page1)
        self.pending_loan_request_page2 = QtWidgets.QWidget()
        self.pending_loan_request_page2.setObjectName("pending_loan_request_page2")
        self.scrollArea = QtWidgets.QScrollArea(self.pending_loan_request_page2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 871, 655))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 869, 653))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.fiplr2_email_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_email_lineedit.setEnabled(False)
        self.fiplr2_email_lineedit.setGeometry(QtCore.QRect(60, 420, 321, 27))
        self.fiplr2_email_lineedit.setObjectName("fiplr2_email_lineedit")
        self.fiplr2_reject_pushbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.fiplr2_reject_pushbutton.setGeometry(QtCore.QRect(100, 750, 111, 31))
        self.fiplr2_reject_pushbutton.setObjectName("fiplr2_reject_pushbutton")
        self.fiplr2_offer_interest_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_offer_interest_label.setGeometry(QtCore.QRect(260, 680, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_offer_interest_label.setFont(font)
        self.fiplr2_offer_interest_label.setObjectName("fiplr2_offer_interest_label")
        self.fiplr2_loan_duration_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_loan_duration_label.setGeometry(QtCore.QRect(540, 680, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_loan_duration_label.setFont(font)
        self.fiplr2_loan_duration_label.setObjectName("fiplr2_loan_duration_label")
        self.fiplr2_lastname_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_lastname_lineedit.setEnabled(False)
        self.fiplr2_lastname_lineedit.setGeometry(QtCore.QRect(240, 210, 141, 27))
        self.fiplr2_lastname_lineedit.setObjectName("fiplr2_lastname_lineedit")
        self.fiplr2_loan_amount_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_loan_amount_label.setGeometry(QtCore.QRect(420, 500, 211, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_loan_amount_label.setFont(font)
        self.fiplr2_loan_amount_label.setObjectName("fiplr2_loan_amount_label")
        self.fiplr2_property_address_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_property_address_label.setGeometry(QtCore.QRect(60, 500, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_property_address_label.setFont(font)
        self.fiplr2_property_address_label.setObjectName("fiplr2_property_address_label")
        self.fiplr2_documents_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_documents_label.setGeometry(QtCore.QRect(430, 180, 90, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_documents_label.setFont(font)
        self.fiplr2_documents_label.setObjectName("fiplr2_documents_label")
        self.fiplr2_personal_information_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_personal_information_label.setGeometry(QtCore.QRect(60, 150, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_personal_information_label.setFont(font)
        self.fiplr2_personal_information_label.setObjectName("fiplr2_personal_information_label")
        self.fiplr2_phonenumber_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_phonenumber_lineedit.setEnabled(False)
        self.fiplr2_phonenumber_lineedit.setGeometry(QtCore.QRect(60, 350, 141, 27))
        self.fiplr2_phonenumber_lineedit.setObjectName("fiplr2_phonenumber_lineedit")
        self.fiplr2_email_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_email_label.setGeometry(QtCore.QRect(60, 390, 181, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_email_label.setFont(font)
        self.fiplr2_email_label.setObjectName("fiplr2_email_label")
        self.fiplr2_risk_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_risk_label.setGeometry(QtCore.QRect(240, 320, 121, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_risk_label.setFont(font)
        self.fiplr2_risk_label.setObjectName("fiplr2_risk_label")
        self.fiplr2_documents_listview = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.fiplr2_documents_listview.setGeometry(QtCore.QRect(430, 210, 281, 231))
        self.fiplr2_documents_listview.setObjectName("fiplr2_documents_listview")
        self.fiplr2_property_value_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_property_value_lineedit.setEnabled(False)
        self.fiplr2_property_value_lineedit.setGeometry(QtCore.QRect(420, 600, 151, 27))
        self.fiplr2_property_value_lineedit.setObjectName("fiplr2_property_value_lineedit")
        self.fiplr2_loan_amount_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_loan_amount_lineedit.setEnabled(False)
        self.fiplr2_loan_amount_lineedit.setGeometry(QtCore.QRect(420, 530, 151, 27))
        self.fiplr2_loan_amount_lineedit.setObjectName("fiplr2_loan_amount_lineedit")
        self.fiplr2_offer_amount_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_offer_amount_lineedit.setGeometry(QtCore.QRect(60, 710, 141, 27))
        self.fiplr2_offer_amount_lineedit.setObjectName("fiplr2_offer_amount_lineedit")
        self.fiplr2_risk_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_risk_lineedit.setEnabled(False)
        self.fiplr2_risk_lineedit.setGeometry(QtCore.QRect(240, 350, 51, 27))
        self.fiplr2_risk_lineedit.setObjectName("fiplr2_risk_lineedit")
        self.fiplr2_offer_amount_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_offer_amount_label.setGeometry(QtCore.QRect(60, 680, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_offer_amount_label.setFont(font)
        self.fiplr2_offer_amount_label.setObjectName("fiplr2_offer_amount_label")
        self.fiplr2_address_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_address_lineedit.setEnabled(False)
        self.fiplr2_address_lineedit.setGeometry(QtCore.QRect(60, 280, 321, 27))
        self.fiplr2_address_lineedit.setObjectName("fiplr2_address_lineedit")
        self.fiplr2_make_offer_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_make_offer_label.setGeometry(QtCore.QRect(60, 650, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_make_offer_label.setFont(font)
        self.fiplr2_make_offer_label.setObjectName("fiplr2_make_offer_label")
        self.fiplr2_address_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_address_label.setGeometry(QtCore.QRect(60, 250, 370, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_address_label.setFont(font)
        self.fiplr2_address_label.setObjectName("fiplr2_address_label")
        self.fiplr2_title_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_title_label.setGeometry(QtCore.QRect(60, 60, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_title_label.setFont(font)
        self.fiplr2_title_label.setObjectName("fiplr2_title_label")
        self.fiplr2_loan_request_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_loan_request_label.setGeometry(QtCore.QRect(60, 120, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_loan_request_label.setFont(font)
        self.fiplr2_loan_request_label.setObjectName("fiplr2_loan_request_label")
        self.fiplr2_mortgage_type_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_mortgage_type_lineedit.setEnabled(False)
        self.fiplr2_mortgage_type_lineedit.setGeometry(QtCore.QRect(60, 600, 151, 27))
        self.fiplr2_mortgage_type_lineedit.setObjectName("fiplr2_mortgage_type_lineedit")
        self.fiplr2_firstname_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_firstname_label.setGeometry(QtCore.QRect(60, 180, 90, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_firstname_label.setFont(font)
        self.fiplr2_firstname_label.setObjectName("fiplr2_firstname_label")
        self.fiplr2_phonenumber_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_phonenumber_label.setGeometry(QtCore.QRect(60, 320, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_phonenumber_label.setFont(font)
        self.fiplr2_phonenumber_label.setObjectName("fiplr2_phonenumber_label")
        self.fiplr2_offer_interest_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_offer_interest_lineedit.setGeometry(QtCore.QRect(260, 710, 81, 27))
        self.fiplr2_offer_interest_lineedit.setObjectName("fiplr2_offer_interest_lineedit")
        self.fiplr2_default_rate_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_default_rate_label.setGeometry(QtCore.QRect(400, 680, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_default_rate_label.setFont(font)
        self.fiplr2_default_rate_label.setObjectName("fiplr2_default_rate_label")
        self.fiplr2_mortgage_information_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_mortgage_information_label.setGeometry(QtCore.QRect(60, 470, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiplr2_mortgage_information_label.setFont(font)
        self.fiplr2_mortgage_information_label.setObjectName("fiplr2_mortgage_information_label")
        self.fiplr2_lastname_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_lastname_label.setGeometry(QtCore.QRect(240, 180, 90, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_lastname_label.setFont(font)
        self.fiplr2_lastname_label.setObjectName("fiplr2_lastname_label")
        self.fiplr2_accept_pushbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.fiplr2_accept_pushbutton.setGeometry(QtCore.QRect(470, 750, 111, 31))
        self.fiplr2_accept_pushbutton.setObjectName("fiplr2_accept_pushbutton")
        self.fiplr2_loan_duration_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_loan_duration_lineedit.setGeometry(QtCore.QRect(540, 710, 91, 27))
        self.fiplr2_loan_duration_lineedit.setObjectName("fiplr2_loan_duration_lineedit")
        self.fiplr2_property_value_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_property_value_label.setGeometry(QtCore.QRect(420, 570, 370, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_property_value_label.setFont(font)
        self.fiplr2_property_value_label.setObjectName("fiplr2_property_value_label")
        self.fiplr2_mortgage_type_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fiplr2_mortgage_type_label.setGeometry(QtCore.QRect(60, 570, 281, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fiplr2_mortgage_type_label.setFont(font)
        self.fiplr2_mortgage_type_label.setObjectName("fiplr2_mortgage_type_label")
        self.fiplr2_default_rate_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_default_rate_lineedit.setGeometry(QtCore.QRect(400, 710, 81, 27))
        self.fiplr2_default_rate_lineedit.setObjectName("fiplr2_default_rate_lineedit")
        self.fiplr2_property_address_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_property_address_lineedit.setEnabled(False)
        self.fiplr2_property_address_lineedit.setGeometry(QtCore.QRect(60, 530, 321, 27))
        self.fiplr2_property_address_lineedit.setObjectName("fiplr2_property_address_lineedit")
        self.fiplr2_firstname_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fiplr2_firstname_lineedit.setEnabled(False)
        self.fiplr2_firstname_lineedit.setGeometry(QtCore.QRect(60, 210, 141, 27))
        self.fiplr2_firstname_lineedit.setObjectName("fiplr2_firstname_lineedit")
        self.prev_6 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.prev_6.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_6.setObjectName("prev_6")
        self.next_6 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.next_6.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_6.setObjectName("next_6")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        StackedWidget.addWidget(self.pending_loan_request_page2)
        self.open_market_page = QtWidgets.QWidget()
        self.open_market_page.setObjectName("open_market_page")
        self.openmarket_duration2_lineedit = QtWidgets.QLineEdit(self.open_market_page)
        self.openmarket_duration2_lineedit.setGeometry(QtCore.QRect(690, 320, 41, 20))
        self.openmarket_duration2_lineedit.setObjectName("openmarket_duration2_lineedit")
        self.openmarket_search_lineedit = QtWidgets.QLineEdit(self.open_market_page)
        self.openmarket_search_lineedit.setGeometry(QtCore.QRect(630, 110, 121, 21))
        self.openmarket_search_lineedit.setObjectName("openmarket_search_lineedit")
        self.openmarket_rating_label = QtWidgets.QLabel(self.open_market_page)
        self.openmarket_rating_label.setGeometry(QtCore.QRect(630, 350, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_rating_label.setFont(font)
        self.openmarket_rating_label.setObjectName("openmarket_rating_label")
        self.openmarket_search_pushbutton = QtWidgets.QPushButton(self.open_market_page)
        self.openmarket_search_pushbutton.setGeometry(QtCore.QRect(750, 110, 75, 21))
        self.openmarket_search_pushbutton.setObjectName("openmarket_search_pushbutton")
        self.openmarket_rating_checkbox_a = QtWidgets.QCheckBox(self.open_market_page)
        self.openmarket_rating_checkbox_a.setGeometry(QtCore.QRect(630, 370, 70, 17))
        self.openmarket_rating_checkbox_a.setObjectName("openmarket_rating_checkbox_a")
        self.openmarket_title_label = QtWidgets.QLabel(self.open_market_page)
        self.openmarket_title_label.setGeometry(QtCore.QRect(60, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_title_label.setFont(font)
        self.openmarket_title_label.setObjectName("openmarket_title_label")
        self.openmarket_interest_dash_label = QtWidgets.QLabel(self.open_market_page)
        self.openmarket_interest_dash_label.setGeometry(QtCore.QRect(680, 270, 16, 16))
        self.openmarket_interest_dash_label.setObjectName("openmarket_interest_dash_label")
        self.openmarket_duration_label = QtWidgets.QLabel(self.open_market_page)
        self.openmarket_duration_label.setGeometry(QtCore.QRect(630, 300, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_duration_label.setFont(font)
        self.openmarket_duration_label.setObjectName("openmarket_duration_label")
        self.openmarket_invest_pushbutton = QtWidgets.QPushButton(self.open_market_page)
        self.openmarket_invest_pushbutton.setGeometry(QtCore.QRect(760, 490, 61, 23))
        self.openmarket_invest_pushbutton.setObjectName("openmarket_invest_pushbutton")
        self.openmarket_duration_dash_label = QtWidgets.QLabel(self.open_market_page)
        self.openmarket_duration_dash_label.setGeometry(QtCore.QRect(680, 320, 16, 16))
        self.openmarket_duration_dash_label.setObjectName("openmarket_duration_dash_label")
        self.openmarket_interest1_lineedit = QtWidgets.QLineEdit(self.open_market_page)
        self.openmarket_interest1_lineedit.setGeometry(QtCore.QRect(630, 270, 41, 20))
        self.openmarket_interest1_lineedit.setObjectName("openmarket_interest1_lineedit")
        self.openmarket_interest_label = QtWidgets.QLabel(self.open_market_page)
        self.openmarket_interest_label.setGeometry(QtCore.QRect(630, 250, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_interest_label.setFont(font)
        self.openmarket_interest_label.setObjectName("openmarket_interest_label")
        self.openmarket_max_amount_lineedit = QtWidgets.QLineEdit(self.open_market_page)
        self.openmarket_max_amount_lineedit.setGeometry(QtCore.QRect(630, 190, 113, 20))
        self.openmarket_max_amount_lineedit.setObjectName("openmarket_max_amount_lineedit")
        self.openmarket_sorting_options_label = QtWidgets.QLabel(self.open_market_page)
        self.openmarket_sorting_options_label.setGeometry(QtCore.QRect(630, 140, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_sorting_options_label.setFont(font)
        self.openmarket_sorting_options_label.setObjectName("openmarket_sorting_options_label")
        self.openmarket_open_market_table = QtWidgets.QTableWidget(self.open_market_page)
        self.openmarket_open_market_table.setGeometry(QtCore.QRect(60, 110, 541, 401))
        self.openmarket_open_market_table.setMaximumSize(QtCore.QSize(641, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_open_market_table.setFont(font)
        self.openmarket_open_market_table.setAlternatingRowColors(False)
        self.openmarket_open_market_table.setObjectName("openmarket_open_market_table")
        self.openmarket_open_market_table.setColumnCount(5)
        self.openmarket_open_market_table.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.openmarket_open_market_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.openmarket_open_market_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.openmarket_open_market_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.openmarket_open_market_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.openmarket_open_market_table.setHorizontalHeaderItem(4, item)
        self.openmarket_open_market_table.horizontalHeader().setDefaultSectionSize(110)
        self.openmarket_open_market_table.horizontalHeader().setStretchLastSection(True)
        self.openmarket_open_market_table.verticalHeader().setStretchLastSection(False)
        self.openmarket_amount_label = QtWidgets.QLabel(self.open_market_page)
        self.openmarket_amount_label.setGeometry(QtCore.QRect(630, 170, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openmarket_amount_label.setFont(font)
        self.openmarket_amount_label.setObjectName("openmarket_amount_label")
        self.openmarket_view_loan_bids_pushbutton = QtWidgets.QPushButton(self.open_market_page)
        self.openmarket_view_loan_bids_pushbutton.setGeometry(QtCore.QRect(630, 490, 111, 22))
        self.openmarket_view_loan_bids_pushbutton.setObjectName("openmarket_view_loan_bids_pushbutton")
        self.openmarket_rating_checkbox_b = QtWidgets.QCheckBox(self.open_market_page)
        self.openmarket_rating_checkbox_b.setGeometry(QtCore.QRect(630, 390, 70, 17))
        self.openmarket_rating_checkbox_b.setObjectName("openmarket_rating_checkbox_b")
        self.openmarket_rating_checkbox_c = QtWidgets.QCheckBox(self.open_market_page)
        self.openmarket_rating_checkbox_c.setGeometry(QtCore.QRect(630, 410, 70, 17))
        self.openmarket_rating_checkbox_c.setObjectName("openmarket_rating_checkbox_c")
        self.openmarket_interest2_lineedit = QtWidgets.QLineEdit(self.open_market_page)
        self.openmarket_interest2_lineedit.setGeometry(QtCore.QRect(690, 270, 41, 20))
        self.openmarket_interest2_lineedit.setObjectName("openmarket_interest2_lineedit")
        self.openmarket_duration1_lineedit = QtWidgets.QLineEdit(self.open_market_page)
        self.openmarket_duration1_lineedit.setGeometry(QtCore.QRect(630, 320, 41, 20))
        self.openmarket_duration1_lineedit.setObjectName("openmarket_duration1_lineedit")
        self.openmarket_min_amount_lineedit = QtWidgets.QLineEdit(self.open_market_page)
        self.openmarket_min_amount_lineedit.setGeometry(QtCore.QRect(630, 220, 113, 20))
        self.openmarket_min_amount_lineedit.setObjectName("openmarket_min_amount_lineedit")
        self.prev_7 = QtWidgets.QToolButton(self.open_market_page)
        self.prev_7.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_7.setObjectName("prev_7")
        self.next_7 = QtWidgets.QToolButton(self.open_market_page)
        self.next_7.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_7.setObjectName("next_7")
        StackedWidget.addWidget(self.open_market_page)
        self.investors_portfolio = QtWidgets.QWidget()
        self.investors_portfolio.setObjectName("investors_portfolio")
        self.ip_duration2_lineedit = QtWidgets.QLineEdit(self.investors_portfolio)
        self.ip_duration2_lineedit.setGeometry(QtCore.QRect(630, 340, 41, 20))
        self.ip_duration2_lineedit.setObjectName("ip_duration2_lineedit")
        self.ip_sorting_options_label = QtWidgets.QLabel(self.investors_portfolio)
        self.ip_sorting_options_label.setGeometry(QtCore.QRect(570, 160, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ip_sorting_options_label.setFont(font)
        self.ip_sorting_options_label.setObjectName("ip_sorting_options_label")
        self.ip_duration_label = QtWidgets.QLabel(self.investors_portfolio)
        self.ip_duration_label.setGeometry(QtCore.QRect(570, 320, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ip_duration_label.setFont(font)
        self.ip_duration_label.setObjectName("ip_duration_label")
        self.ip_search_pushbutton = QtWidgets.QPushButton(self.investors_portfolio)
        self.ip_search_pushbutton.setGeometry(QtCore.QRect(670, 130, 75, 23))
        self.ip_search_pushbutton.setObjectName("ip_search_pushbutton")
        self.ip_resell_pushbutton = QtWidgets.QPushButton(self.investors_portfolio)
        self.ip_resell_pushbutton.setGeometry(QtCore.QRect(480, 410, 75, 23))
        self.ip_resell_pushbutton.setObjectName("ip_resell_pushbutton")
        self.ip_interest2_lineedit = QtWidgets.QLineEdit(self.investors_portfolio)
        self.ip_interest2_lineedit.setGeometry(QtCore.QRect(630, 290, 41, 20))
        self.ip_interest2_lineedit.setObjectName("ip_interest2_lineedit")
        self.ip_duration_dash_label = QtWidgets.QLabel(self.investors_portfolio)
        self.ip_duration_dash_label.setGeometry(QtCore.QRect(620, 340, 16, 16))
        self.ip_duration_dash_label.setObjectName("ip_duration_dash_label")
        self.ip_investing_opportunities_table = QtWidgets.QTableWidget(self.investors_portfolio)
        self.ip_investing_opportunities_table.setEnabled(False)
        self.ip_investing_opportunities_table.setGeometry(QtCore.QRect(60, 890, 491, 161))
        self.ip_investing_opportunities_table.setMaximumSize(QtCore.QSize(641, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ip_investing_opportunities_table.setFont(font)
        self.ip_investing_opportunities_table.setAlternatingRowColors(False)
        self.ip_investing_opportunities_table.setObjectName("ip_investing_opportunities_table")
        self.ip_investing_opportunities_table.setColumnCount(4)
        self.ip_investing_opportunities_table.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_investing_opportunities_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ip_investing_opportunities_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ip_investing_opportunities_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ip_investing_opportunities_table.setHorizontalHeaderItem(3, item)
        self.ip_investing_opportunities_table.horizontalHeader().setDefaultSectionSize(110)
        self.ip_investing_opportunities_table.horizontalHeader().setStretchLastSection(True)
        self.ip_ongoing_investments_label = QtWidgets.QLabel(self.investors_portfolio)
        self.ip_ongoing_investments_label.setGeometry(QtCore.QRect(60, 100, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ip_ongoing_investments_label.setFont(font)
        self.ip_ongoing_investments_label.setObjectName("ip_ongoing_investments_label")
        self.ip_interest_dash_label = QtWidgets.QLabel(self.investors_portfolio)
        self.ip_interest_dash_label.setGeometry(QtCore.QRect(620, 290, 16, 16))
        self.ip_interest_dash_label.setObjectName("ip_interest_dash_label")
        self.ip_investors_portfolio_label = QtWidgets.QLabel(self.investors_portfolio)
        self.ip_investors_portfolio_label.setGeometry(QtCore.QRect(60, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ip_investors_portfolio_label.setFont(font)
        self.ip_investors_portfolio_label.setObjectName("ip_investors_portfolio_label")
        self.ip_duration1_lineedit = QtWidgets.QLineEdit(self.investors_portfolio)
        self.ip_duration1_lineedit.setGeometry(QtCore.QRect(570, 340, 41, 20))
        self.ip_duration1_lineedit.setObjectName("ip_duration1_lineedit")
        self.ip_ongoing_investments_table = QtWidgets.QTableWidget(self.investors_portfolio)
        self.ip_ongoing_investments_table.setGeometry(QtCore.QRect(60, 130, 491, 260))
        self.ip_ongoing_investments_table.setMaximumSize(QtCore.QSize(641, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ip_ongoing_investments_table.setFont(font)
        self.ip_ongoing_investments_table.setAlternatingRowColors(False)
        self.ip_ongoing_investments_table.setObjectName("ip_ongoing_investments_table")
        self.ip_ongoing_investments_table.setColumnCount(6)
        self.ip_ongoing_investments_table.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_ongoing_investments_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ip_ongoing_investments_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ip_ongoing_investments_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ip_ongoing_investments_table.setHorizontalHeaderItem(5, item)
        self.ip_ongoing_investments_table.horizontalHeader().setDefaultSectionSize(110)
        self.ip_ongoing_investments_table.horizontalHeader().setStretchLastSection(True)
        self.ip_min_amount_lineedit = QtWidgets.QLineEdit(self.investors_portfolio)
        self.ip_min_amount_lineedit.setGeometry(QtCore.QRect(570, 240, 113, 20))
        self.ip_min_amount_lineedit.setObjectName("ip_min_amount_lineedit")
        self.ip_reject_pushbutton = QtWidgets.QPushButton(self.investors_portfolio)
        self.ip_reject_pushbutton.setEnabled(False)
        self.ip_reject_pushbutton.setGeometry(QtCore.QRect(400, 1060, 75, 23))
        self.ip_reject_pushbutton.setObjectName("ip_reject_pushbutton")
        self.ip_amount_invested_label = QtWidgets.QLabel(self.investors_portfolio)
        self.ip_amount_invested_label.setGeometry(QtCore.QRect(570, 190, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ip_amount_invested_label.setFont(font)
        self.ip_amount_invested_label.setObjectName("ip_amount_invested_label")
        self.ip_max_lineedit = QtWidgets.QLineEdit(self.investors_portfolio)
        self.ip_max_lineedit.setGeometry(QtCore.QRect(570, 210, 113, 20))
        self.ip_max_lineedit.setObjectName("ip_max_lineedit")
        self.ip_investing_opportunities_label = QtWidgets.QLabel(self.investors_portfolio)
        self.ip_investing_opportunities_label.setEnabled(False)
        self.ip_investing_opportunities_label.setGeometry(QtCore.QRect(60, 860, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ip_investing_opportunities_label.setFont(font)
        self.ip_investing_opportunities_label.setObjectName("ip_investing_opportunities_label")
        self.ip_interest_label = QtWidgets.QLabel(self.investors_portfolio)
        self.ip_interest_label.setGeometry(QtCore.QRect(570, 270, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ip_interest_label.setFont(font)
        self.ip_interest_label.setObjectName("ip_interest_label")
        self.ip_interest1_lineedit = QtWidgets.QLineEdit(self.investors_portfolio)
        self.ip_interest1_lineedit.setGeometry(QtCore.QRect(570, 290, 41, 20))
        self.ip_interest1_lineedit.setObjectName("ip_interest1_lineedit")
        self.ip_accept_pushbutton = QtWidgets.QPushButton(self.investors_portfolio)
        self.ip_accept_pushbutton.setEnabled(False)
        self.ip_accept_pushbutton.setGeometry(QtCore.QRect(480, 1060, 75, 23))
        self.ip_accept_pushbutton.setObjectName("ip_accept_pushbutton")
        self.ip_search_lineedit = QtWidgets.QLineEdit(self.investors_portfolio)
        self.ip_search_lineedit.setGeometry(QtCore.QRect(570, 130, 91, 21))
        self.ip_search_lineedit.setObjectName("ip_search_lineedit")
        self.prev_8 = QtWidgets.QToolButton(self.investors_portfolio)
        self.prev_8.setGeometry(QtCore.QRect(20, 10, 22, 25))
        self.prev_8.setObjectName("prev_8")
        self.next_8 = QtWidgets.QToolButton(self.investors_portfolio)
        self.next_8.setGeometry(QtCore.QRect(40, 10, 22, 25))
        self.next_8.setObjectName("next_8")
        StackedWidget.addWidget(self.investors_portfolio)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)
        StackedWidget.setTabOrder(self.ip_ongoing_investments_table, self.ip_search_lineedit)
        StackedWidget.setTabOrder(self.ip_search_lineedit, self.ip_search_pushbutton)
        StackedWidget.setTabOrder(self.ip_search_pushbutton, self.ip_max_lineedit)
        StackedWidget.setTabOrder(self.ip_max_lineedit, self.ip_min_amount_lineedit)
        StackedWidget.setTabOrder(self.ip_min_amount_lineedit, self.ip_interest1_lineedit)
        StackedWidget.setTabOrder(self.ip_interest1_lineedit, self.ip_interest2_lineedit)
        StackedWidget.setTabOrder(self.ip_interest2_lineedit, self.ip_duration1_lineedit)
        StackedWidget.setTabOrder(self.ip_duration1_lineedit, self.ip_duration2_lineedit)
        StackedWidget.setTabOrder(self.ip_duration2_lineedit, self.ip_resell_pushbutton)
        StackedWidget.setTabOrder(self.ip_resell_pushbutton, self.profile_housenumber_lineedit)
        StackedWidget.setTabOrder(self.profile_housenumber_lineedit, self.profile_email_lineedit)
        StackedWidget.setTabOrder(self.profile_email_lineedit, self.profile_lastname_lineedit)
        StackedWidget.setTabOrder(self.profile_lastname_lineedit, self.profile_investor_radiobutton)
        StackedWidget.setTabOrder(self.profile_investor_radiobutton, self.profile_documents_table)
        StackedWidget.setTabOrder(self.profile_documents_table, self.profile_firstname_lineedit)
        StackedWidget.setTabOrder(self.profile_firstname_lineedit, self.profile_save_button)
        StackedWidget.setTabOrder(self.profile_save_button, self.bplr_housenumber_lineedit)
        StackedWidget.setTabOrder(self.bplr_housenumber_lineedit, self.bplr_house_price_lineedit)
        StackedWidget.setTabOrder(self.bplr_house_price_lineedit, self.bplr_postcode_lineedit)
        StackedWidget.setTabOrder(self.bplr_postcode_lineedit, self.bplr_seller_phone_number_lineedit)
        StackedWidget.setTabOrder(self.bplr_seller_phone_number_lineedit, self.bplr_house_link_lineedit)
        StackedWidget.setTabOrder(self.bplr_house_link_lineedit, self.bplr_submit_button)
        StackedWidget.setTabOrder(self.bplr_submit_button, self.bplr_amount_wanted_lineedit)
        StackedWidget.setTabOrder(self.bplr_amount_wanted_lineedit, self.bplr_linear_radiobutton)
        StackedWidget.setTabOrder(self.bplr_linear_radiobutton, self.bplr_fixedrate_radiobutton)
        StackedWidget.setTabOrder(self.bplr_fixedrate_radiobutton, self.bplr_description_textedit)
        StackedWidget.setTabOrder(self.bplr_description_textedit, self.bplr_bank2_checkbox)
        StackedWidget.setTabOrder(self.bplr_bank2_checkbox, self.bplr_bank1_checkbox)
        StackedWidget.setTabOrder(self.bplr_bank1_checkbox, self.bplr_bank3_checkbox)
        StackedWidget.setTabOrder(self.bplr_bank3_checkbox, self.bplr_bank4_checkbox)
        StackedWidget.setTabOrder(self.bplr_bank4_checkbox, self.bplr_seller_email_lineedit)
        StackedWidget.setTabOrder(self.bplr_seller_email_lineedit, self.bp_open_offers_table)
        StackedWidget.setTabOrder(self.bp_open_offers_table, self.bp_reject_pushbutton)
        StackedWidget.setTabOrder(self.bp_reject_pushbutton, self.bp_accept_pushbutton)
        StackedWidget.setTabOrder(self.bp_accept_pushbutton, self.bp_ongoing_loans_table)
        StackedWidget.setTabOrder(self.bp_ongoing_loans_table, self.fiplr1_pushbutton)
        StackedWidget.setTabOrder(self.fiplr1_pushbutton, self.fiplr1_loan_requests_table)
        StackedWidget.setTabOrder(self.fiplr1_loan_requests_table, self.scrollArea)
        StackedWidget.setTabOrder(self.scrollArea, self.fiplr2_email_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_email_lineedit, self.fiplr2_reject_pushbutton)
        StackedWidget.setTabOrder(self.fiplr2_reject_pushbutton, self.fiplr2_lastname_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_lastname_lineedit, self.fiplr2_phonenumber_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_phonenumber_lineedit, self.fiplr2_documents_listview)
        StackedWidget.setTabOrder(self.fiplr2_documents_listview, self.fiplr2_property_value_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_property_value_lineedit, self.fiplr2_loan_amount_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_loan_amount_lineedit, self.fiplr2_offer_amount_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_offer_amount_lineedit, self.fiplr2_risk_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_risk_lineedit, self.fiplr2_address_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_address_lineedit, self.fiplr2_mortgage_type_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_mortgage_type_lineedit, self.fiplr2_offer_interest_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_offer_interest_lineedit, self.fiplr2_accept_pushbutton)
        StackedWidget.setTabOrder(self.fiplr2_accept_pushbutton, self.fiplr2_loan_duration_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_loan_duration_lineedit, self.fiplr2_default_rate_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_default_rate_lineedit, self.fiplr2_property_address_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_property_address_lineedit, self.fiplr2_firstname_lineedit)
        StackedWidget.setTabOrder(self.fiplr2_firstname_lineedit, self.openmarket_duration2_lineedit)
        StackedWidget.setTabOrder(self.openmarket_duration2_lineedit, self.openmarket_search_lineedit)
        StackedWidget.setTabOrder(self.openmarket_search_lineedit, self.openmarket_search_pushbutton)
        StackedWidget.setTabOrder(self.openmarket_search_pushbutton, self.openmarket_rating_checkbox_a)
        StackedWidget.setTabOrder(self.openmarket_rating_checkbox_a, self.openmarket_invest_pushbutton)
        StackedWidget.setTabOrder(self.openmarket_invest_pushbutton, self.openmarket_interest1_lineedit)
        StackedWidget.setTabOrder(self.openmarket_interest1_lineedit, self.openmarket_max_amount_lineedit)
        StackedWidget.setTabOrder(self.openmarket_max_amount_lineedit, self.openmarket_open_market_table)
        StackedWidget.setTabOrder(self.openmarket_open_market_table, self.openmarket_view_loan_bids_pushbutton)
        StackedWidget.setTabOrder(self.openmarket_view_loan_bids_pushbutton, self.openmarket_rating_checkbox_b)
        StackedWidget.setTabOrder(self.openmarket_rating_checkbox_b, self.openmarket_rating_checkbox_c)
        StackedWidget.setTabOrder(self.openmarket_rating_checkbox_c, self.openmarket_interest2_lineedit)
        StackedWidget.setTabOrder(self.openmarket_interest2_lineedit, self.openmarket_duration1_lineedit)
        StackedWidget.setTabOrder(self.openmarket_duration1_lineedit, self.openmarket_min_amount_lineedit)
        StackedWidget.setTabOrder(self.openmarket_min_amount_lineedit, self.profile_postcode_lineedit)
        StackedWidget.setTabOrder(self.profile_postcode_lineedit, self.login_generate_button)
        StackedWidget.setTabOrder(self.login_generate_button, self.profile_borrower_radiobutton)
        StackedWidget.setTabOrder(self.profile_borrower_radiobutton, self.profile_phonenumber_lineedit)
        StackedWidget.setTabOrder(self.profile_phonenumber_lineedit, self.ip_investing_opportunities_table)
        StackedWidget.setTabOrder(self.ip_investing_opportunities_table, self.profile_address_lineedit)
        StackedWidget.setTabOrder(self.profile_address_lineedit, self.login_browse_button)
        StackedWidget.setTabOrder(self.login_browse_button, self.login_push_button)
        StackedWidget.setTabOrder(self.login_push_button, self.ip_reject_pushbutton)
        StackedWidget.setTabOrder(self.ip_reject_pushbutton, self.login_private_key_line)
        StackedWidget.setTabOrder(self.login_private_key_line, self.profile_iban_lineedit)
        StackedWidget.setTabOrder(self.profile_iban_lineedit, self.ip_accept_pushbutton)
        StackedWidget.setTabOrder(self.ip_accept_pushbutton, self.login_remember_me_checkbox)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.login_title.setText(_translate("StackedWidget", "<html><head/><body><p><span style=\" font-weight:600;\">Login</span></p></body></html>"))
        self.login_browse_button.setText(_translate("StackedWidget", "Browse"))
        self.login_remember_me_checkbox.setText(_translate("StackedWidget", "Remember Me"))
        self.login_private_key_label.setText(_translate("StackedWidget", "<html><head/><body><p><span style=\" font-weight:600;\">Private key</span></p></body></html>"))
        self.login_generate_button.setText(_translate("StackedWidget", "Generate "))
        self.login_push_button.setText(_translate("StackedWidget", "Login"))
        self.login_no_private_key_label.setText(_translate("StackedWidget", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Don\'t have a private key?</span></p></body></html>"))
        self.prev_1.setText(_translate("StackedWidget", "<"))
        self.next_1.setText(_translate("StackedWidget", ">"))
        self.profile_email_label.setText(_translate("StackedWidget", "Email Address"))
        self.profile_firstname_label.setText(_translate("StackedWidget", "First Name"))
        self.profile_housenumber_label.setText(_translate("StackedWidget", "Current House Number"))
        self.profile_address_label.setText(_translate("StackedWidget", "Current Address"))
        self.role_label.setText(_translate("StackedWidget", "I am a:"))
        self.profile_postcode_label.setText(_translate("StackedWidget", "Current Post Code"))
        self.profile_lastname_label.setText(_translate("StackedWidget", "Last Name"))
        self.profile_title.setText(_translate("StackedWidget", "Profile"))
        self.profile_borrower_radiobutton.setText(_translate("StackedWidget", "Borrower"))
        self.profile_phonenumber_label.setText(_translate("StackedWidget", "Telephone Number"))
        self.profile_iban_label.setText(_translate("StackedWidget", "IBAN"))
        self.profile_documents_label.setText(_translate("StackedWidget", "Documents"))
        self.profile_investor_radiobutton.setText(_translate("StackedWidget", "Investor"))
        item = self.profile_documents_table.verticalHeaderItem(0)
        item.setText(_translate("StackedWidget", "Example Document 1"))
        item = self.profile_documents_table.verticalHeaderItem(1)
        item.setText(_translate("StackedWidget", "Example Document 2"))
        item = self.profile_documents_table.verticalHeaderItem(2)
        item.setText(_translate("StackedWidget", "Example Document 3"))
        item = self.profile_documents_table.verticalHeaderItem(3)
        item.setText(_translate("StackedWidget", "Example Document 4"))
        item = self.profile_documents_table.verticalHeaderItem(4)
        item.setText(_translate("StackedWidget", "Example Document 5"))
        self.profile_save_button.setText(_translate("StackedWidget", "Save Changes"))
        self.next_2.setText(_translate("StackedWidget", ">"))
        self.prev_2.setText(_translate("StackedWidget", "<"))
        self.bplr_title_label.setText(_translate("StackedWidget", "Place Loan Request"))
        self.bplr_postcode_label.setText(_translate("StackedWidget", "Post Code"))
        self.bplr_submit_button.setText(_translate("StackedWidget", "Submit Loan Request"))
        self.bplr_mortgage_information_label.setText(_translate("StackedWidget", "Mortgage Information"))
        self.bplr_housenumber_label.setText(_translate("StackedWidget", "House Number"))
        self.bplr_mortgage_type_label.setText(_translate("StackedWidget", "Mortgage Type"))
        self.bplr_house_price_label.setText(_translate("StackedWidget", "House Price (€)"))
        self.bplr_preferred_banks_label.setText(_translate("StackedWidget", "Preferred Banks"))
        self.bplr_seller_phone_number_label.setText(_translate("StackedWidget", "Phone Number"))
        self.bplr_amount_wanted_label.setText(_translate("StackedWidget", "Amount Wanted (€)"))
        self.bplr_linear_radiobutton.setText(_translate("StackedWidget", "Linear"))
        self.bplr_fixedrate_radiobutton.setText(_translate("StackedWidget", "Fixed-Rate"))
        self.bplr_house_link_label.setText(_translate("StackedWidget", "Link to House [optional]"))
        self.bplr_property_information_label.setText(_translate("StackedWidget", "Property Information"))
        self.bplr_description_label.setText(_translate("StackedWidget", "Describe here why you want a loan for this house [optional]"))
        self.bplr_personal_information_label.setText(_translate("StackedWidget", "Personal Information"))
        self.bplr_bank2_checkbox.setText(_translate("StackedWidget", "Bank 2"))
        self.bplr_bank1_checkbox.setText(_translate("StackedWidget", "Bank 1"))
        self.bplr_bank3_checkbox.setText(_translate("StackedWidget", "Bank 3"))
        self.bplr_bank4_checkbox.setText(_translate("StackedWidget", "Bank 4"))
        self.bplr_property_seller_information_label.setText(_translate("StackedWidget", "Property Seller Information"))
        self.bplr_seller_email_label.setText(_translate("StackedWidget", "Email address [optional]"))
        self.prev_3.setText(_translate("StackedWidget", "<"))
        self.next_3.setText(_translate("StackedWidget", ">"))
        item = self.bp_open_offers_table.horizontalHeaderItem(0)
        item.setText(_translate("StackedWidget", "Loan Amount (€)"))
        item = self.bp_open_offers_table.horizontalHeaderItem(1)
        item.setText(_translate("StackedWidget", "Interest (%)"))
        item = self.bp_open_offers_table.horizontalHeaderItem(2)
        item.setText(_translate("StackedWidget", "Default (%)"))
        item = self.bp_open_offers_table.horizontalHeaderItem(3)
        item.setText(_translate("StackedWidget", "Duration (month)"))
        item = self.bp_open_offers_table.horizontalHeaderItem(4)
        item.setText(_translate("StackedWidget", "Type"))
        self.bp_reject_pushbutton.setText(_translate("StackedWidget", "Reject"))
        self.bp_open_offers_label.setText(_translate("StackedWidget", "<html><head/><body><p><span style=\" font-size:12pt;\">Open offers</span></p></body></html>"))
        self.bp_accept_pushbutton.setText(_translate("StackedWidget", "Accept"))
        self.bp_ongoing_loans_label.setText(_translate("StackedWidget", "<html><head/><body><p><span style=\" font-weight:600;\">Overview ongoing loans</span></p></body></html>"))
        self.bp_title_label.setText(_translate("StackedWidget", "Borrower\'s Portfolio"))
        item = self.bp_ongoing_loans_table.horizontalHeaderItem(0)
        item.setText(_translate("StackedWidget", "Loan Amount (€)"))
        item = self.bp_ongoing_loans_table.horizontalHeaderItem(1)
        item.setText(_translate("StackedWidget", "Interest (%)"))
        item = self.bp_ongoing_loans_table.horizontalHeaderItem(2)
        item.setText(_translate("StackedWidget", "Default (%)"))
        item = self.bp_ongoing_loans_table.horizontalHeaderItem(3)
        item.setText(_translate("StackedWidget", "Duration (month)"))
        item = self.bp_ongoing_loans_table.horizontalHeaderItem(4)
        item.setText(_translate("StackedWidget", "Type"))
        self.prev_4.setText(_translate("StackedWidget", "<"))
        self.next_4.setText(_translate("StackedWidget", ">"))
        self.fiplr1_pending_loan_requests_label.setText(_translate("StackedWidget", "Pending Loan Requests"))
        self.fiplr1_pushbutton.setText(_translate("StackedWidget", "View loan request"))
        item = self.fiplr1_loan_requests_table.horizontalHeaderItem(0)
        item.setText(_translate("StackedWidget", "Property Address"))
        item = self.fiplr1_loan_requests_table.horizontalHeaderItem(1)
        item.setText(_translate("StackedWidget", "Mortgage Type"))
        item = self.fiplr1_loan_requests_table.horizontalHeaderItem(2)
        item.setText(_translate("StackedWidget", "Loan Amount"))
        item = self.fiplr1_loan_requests_table.horizontalHeaderItem(3)
        item.setText(_translate("StackedWidget", "House Price"))
        self.prev_5.setText(_translate("StackedWidget", "<"))
        self.next_5.setText(_translate("StackedWidget", ">"))
        self.fiplr2_reject_pushbutton.setText(_translate("StackedWidget", "Reject"))
        self.fiplr2_offer_interest_label.setText(_translate("StackedWidget", "Interest (%)"))
        self.fiplr2_loan_duration_label.setText(_translate("StackedWidget", "Loan Duration (months)"))
        self.fiplr2_loan_amount_label.setText(_translate("StackedWidget", "Requested Loan Amount"))
        self.fiplr2_property_address_label.setText(_translate("StackedWidget", "Property Address"))
        self.fiplr2_documents_label.setText(_translate("StackedWidget", "Documents"))
        self.fiplr2_personal_information_label.setText(_translate("StackedWidget", "Personal Information"))
        self.fiplr2_email_label.setText(_translate("StackedWidget", "Email Address"))
        self.fiplr2_risk_label.setText(_translate("StackedWidget", "Current Risk Rating"))
        self.fiplr2_offer_amount_label.setText(_translate("StackedWidget", "Loan Amount Offered (€)"))
        self.fiplr2_make_offer_label.setText(_translate("StackedWidget", "Make Offer"))
        self.fiplr2_address_label.setText(_translate("StackedWidget", "Address"))
        self.fiplr2_title_label.setText(_translate("StackedWidget", "Pending Loan Requests"))
        self.fiplr2_loan_request_label.setText(_translate("StackedWidget", "Loan Request"))
        self.fiplr2_firstname_label.setText(_translate("StackedWidget", "First Name"))
        self.fiplr2_phonenumber_label.setText(_translate("StackedWidget", "Telephone Number"))
        self.fiplr2_default_rate_label.setText(_translate("StackedWidget", "Default Rate"))
        self.fiplr2_mortgage_information_label.setText(_translate("StackedWidget", "Mortgage Request Information"))
        self.fiplr2_lastname_label.setText(_translate("StackedWidget", "Last Name"))
        self.fiplr2_accept_pushbutton.setText(_translate("StackedWidget", "Accept"))
        self.fiplr2_property_value_label.setText(_translate("StackedWidget", "Property Value"))
        self.fiplr2_mortgage_type_label.setText(_translate("StackedWidget", "Mortgage Type"))
        self.prev_6.setText(_translate("StackedWidget", "<"))
        self.next_6.setText(_translate("StackedWidget", ">"))
        self.openmarket_duration2_lineedit.setText(_translate("StackedWidget", "36"))
        self.openmarket_search_lineedit.setText(_translate("StackedWidget", "Type to search..."))
        self.openmarket_rating_label.setText(_translate("StackedWidget", "Rating"))
        self.openmarket_search_pushbutton.setText(_translate("StackedWidget", "Search"))
        self.openmarket_rating_checkbox_a.setText(_translate("StackedWidget", "A"))
        self.openmarket_title_label.setText(_translate("StackedWidget", "Open Market"))
        self.openmarket_interest_dash_label.setText(_translate("StackedWidget", "-"))
        self.openmarket_duration_label.setText(_translate("StackedWidget", "Duration (month)"))
        self.openmarket_invest_pushbutton.setText(_translate("StackedWidget", "Invest"))
        self.openmarket_duration_dash_label.setText(_translate("StackedWidget", "-"))
        self.openmarket_interest1_lineedit.setText(_translate("StackedWidget", "0"))
        self.openmarket_interest_label.setText(_translate("StackedWidget", "Interest (%)"))
        self.openmarket_max_amount_lineedit.setText(_translate("StackedWidget", "Max"))
        self.openmarket_sorting_options_label.setText(_translate("StackedWidget", "Sorting Options"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(0)
        item.setText(_translate("StackedWidget", "Property Address"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(1)
        item.setText(_translate("StackedWidget", "Amount (€)"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(2)
        item.setText(_translate("StackedWidget", "Interest (%)"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(3)
        item.setText(_translate("StackedWidget", "Duration (month)"))
        item = self.openmarket_open_market_table.horizontalHeaderItem(4)
        item.setText(_translate("StackedWidget", "Risk"))
        self.openmarket_amount_label.setText(_translate("StackedWidget", "Amount (€)"))
        self.openmarket_view_loan_bids_pushbutton.setText(_translate("StackedWidget", "View loan bids"))
        self.openmarket_rating_checkbox_b.setText(_translate("StackedWidget", "B"))
        self.openmarket_rating_checkbox_c.setText(_translate("StackedWidget", "C"))
        self.openmarket_interest2_lineedit.setText(_translate("StackedWidget", "100"))
        self.openmarket_duration1_lineedit.setText(_translate("StackedWidget", "12"))
        self.openmarket_min_amount_lineedit.setText(_translate("StackedWidget", "Min"))
        self.prev_7.setText(_translate("StackedWidget", "<"))
        self.next_7.setText(_translate("StackedWidget", ">"))
        self.ip_duration2_lineedit.setText(_translate("StackedWidget", "36"))
        self.ip_sorting_options_label.setText(_translate("StackedWidget", "<html><head/><body><p><span style=\" font-weight:600;\">Sorting Options</span></p></body></html>"))
        self.ip_duration_label.setText(_translate("StackedWidget", "Duration (month)"))
        self.ip_search_pushbutton.setText(_translate("StackedWidget", "Search"))
        self.ip_resell_pushbutton.setText(_translate("StackedWidget", "Resell"))
        self.ip_interest2_lineedit.setText(_translate("StackedWidget", "100"))
        self.ip_duration_dash_label.setText(_translate("StackedWidget", "-"))
        item = self.ip_investing_opportunities_table.horizontalHeaderItem(0)
        item.setText(_translate("StackedWidget", "Property Address"))
        item = self.ip_investing_opportunities_table.horizontalHeaderItem(1)
        item.setText(_translate("StackedWidget", "Amount Invested (€)"))
        item = self.ip_investing_opportunities_table.horizontalHeaderItem(2)
        item.setText(_translate("StackedWidget", " (%)"))
        item = self.ip_investing_opportunities_table.horizontalHeaderItem(3)
        item.setText(_translate("StackedWidget", "Duration (month)"))
        self.ip_ongoing_investments_label.setText(_translate("StackedWidget", "<html><head/><body><p><span style=\" font-weight:600;\">Overview ongoing investments</span></p></body></html>"))
        self.ip_interest_dash_label.setText(_translate("StackedWidget", "-"))
        self.ip_investors_portfolio_label.setText(_translate("StackedWidget", "Investor\'s Portfolio"))
        self.ip_duration1_lineedit.setText(_translate("StackedWidget", "12"))
        item = self.ip_ongoing_investments_table.horizontalHeaderItem(0)
        item.setText(_translate("StackedWidget", "Property Address"))
        item = self.ip_ongoing_investments_table.horizontalHeaderItem(1)
        item.setText(_translate("StackedWidget", "Campaign Status"))
        item = self.ip_ongoing_investments_table.horizontalHeaderItem(2)
        item.setText(_translate("StackedWidget", "Investment Status"))
        item = self.ip_ongoing_investments_table.horizontalHeaderItem(3)
        item.setText(_translate("StackedWidget", "Amount Invested (€)"))
        item = self.ip_ongoing_investments_table.horizontalHeaderItem(4)
        item.setText(_translate("StackedWidget", "Interest (%)"))
        item = self.ip_ongoing_investments_table.horizontalHeaderItem(5)
        item.setText(_translate("StackedWidget", "Duration (month)"))
        self.ip_min_amount_lineedit.setText(_translate("StackedWidget", "Min"))
        self.ip_reject_pushbutton.setText(_translate("StackedWidget", "Reject"))
        self.ip_amount_invested_label.setText(_translate("StackedWidget", "Amount invested (€)"))
        self.ip_max_lineedit.setText(_translate("StackedWidget", "Max"))
        self.ip_investing_opportunities_label.setText(_translate("StackedWidget", "<html><head/><body><p><span style=\" font-weight:600;\">Investing opportunities</span></p></body></html>"))
        self.ip_interest_label.setText(_translate("StackedWidget", "Interest (%)"))
        self.ip_interest1_lineedit.setText(_translate("StackedWidget", "0"))
        self.ip_accept_pushbutton.setText(_translate("StackedWidget", "Accept"))
        self.ip_search_lineedit.setText(_translate("StackedWidget", "Type to search..."))
        self.prev_8.setText(_translate("StackedWidget", "<"))
        self.next_8.setText(_translate("StackedWidget", ">"))

