# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/profileS10058.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(10, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 57, 21))
        self.label_2.setObjectName("label_2")
        self.radioButtonBorrower = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonBorrower.setGeometry(QtCore.QRect(70, 40, 104, 22))
        self.radioButtonBorrower.setObjectName("radioButtonBorrower")
        self.radioButtonInvestor = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonInvestor.setGeometry(QtCore.QRect(180, 40, 104, 22))
        self.radioButtonInvestor.setChecked(True)
        self.radioButtonInvestor.setObjectName("radioButtonInvestor")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 131, 17))
        self.label_3.setObjectName("label_3")
        self.firstNameField = QtWidgets.QLineEdit(self.centralwidget)
        self.firstNameField.setGeometry(QtCore.QRect(20, 90, 191, 27))
        self.firstNameField.setObjectName("firstNameField")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 70, 211, 17))
        self.label_4.setObjectName("label_4")
        self.lastNameField = QtWidgets.QLineEdit(self.centralwidget)
        self.lastNameField.setGeometry(QtCore.QRect(230, 90, 191, 27))
        self.lastNameField.setObjectName("lastNameField")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 141, 17))
        self.label_5.setObjectName("label_5")
        self.curPostalCodeField = QtWidgets.QLineEdit(self.centralwidget)
        self.curPostalCodeField.setEnabled(False)
        self.curPostalCodeField.setGeometry(QtCore.QRect(20, 150, 191, 27))
        self.curPostalCodeField.setObjectName("curPostalCodeField")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 130, 171, 17))
        self.label_6.setObjectName("label_6")
        self.curHouseNumberField = QtWidgets.QLineEdit(self.centralwidget)
        self.curHouseNumberField.setEnabled(False)
        self.curHouseNumberField.setGeometry(QtCore.QRect(230, 150, 191, 27))
        self.curHouseNumberField.setObjectName("curHouseNumberField")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 190, 141, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 250, 141, 17))
        self.label_8.setObjectName("label_8")
        self.telNumberField = QtWidgets.QLineEdit(self.centralwidget)
        self.telNumberField.setEnabled(True)
        self.telNumberField.setGeometry(QtCore.QRect(230, 270, 191, 27))
        self.telNumberField.setObjectName("telNumberField")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 250, 141, 17))
        self.label_9.setObjectName("label_9")
        self.emailAddressField = QtWidgets.QLineEdit(self.centralwidget)
        self.emailAddressField.setGeometry(QtCore.QRect(20, 270, 191, 27))
        self.emailAddressField.setObjectName("emailAddressField")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 370, 181, 17))
        self.label_10.setObjectName("label_10")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(430, 520, 121, 27))
        self.saveButton.setObjectName("saveButton")
        self.documentsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.documentsTable.setEnabled(False)
        self.documentsTable.setGeometry(QtCore.QRect(20, 390, 541, 101))
        self.documentsTable.setObjectName("documentsTable")
        self.documentsTable.setColumnCount(0)
        self.documentsTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentsTable.setVerticalHeaderItem(4, item)
        self.curAddressField = QtWidgets.QLineEdit(self.centralwidget)
        self.curAddressField.setEnabled(False)
        self.curAddressField.setGeometry(QtCore.QRect(20, 210, 401, 31))
        self.curAddressField.setObjectName("curAddressField")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 310, 57, 17))
        self.label_11.setObjectName("label_11")
        self.IBANField = QtWidgets.QLineEdit(self.centralwidget)
        self.IBANField.setGeometry(QtCore.QRect(20, 330, 401, 27))
        self.IBANField.setObjectName("IBANField")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.radioButtonInvestor.toggled['bool'].connect(self.curHouseNumberField.setDisabled)
        self.radioButtonInvestor.toggled['bool'].connect(self.curPostalCodeField.setDisabled)
        self.radioButtonInvestor.toggled['bool'].connect(self.documentsTable.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Profile"))
        self.label_2.setText(_translate("MainWindow", "I am a:"))
        self.radioButtonBorrower.setText(_translate("MainWindow", "Borrower"))
        self.radioButtonInvestor.setText(_translate("MainWindow", "Investor"))
        self.label_3.setText(_translate("MainWindow", "First Name"))
        self.label_4.setText(_translate("MainWindow", "Last Name"))
        self.label_5.setText(_translate("MainWindow", "Current Post Code"))
        self.label_6.setText(_translate("MainWindow", "Current House Number"))
        self.label_7.setText(_translate("MainWindow", "Current Address"))
        self.label_8.setText(_translate("MainWindow", "Telephone Number"))
        self.label_9.setText(_translate("MainWindow", "Email Address"))
        self.label_10.setText(_translate("MainWindow", "Documents"))
        self.saveButton.setText(_translate("MainWindow", "Save Changes"))
        item = self.documentsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Example Document 1"))
        item = self.documentsTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Example Document 2"))
        item = self.documentsTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Example Document 3"))
        item = self.documentsTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Example Document 4"))
        item = self.documentsTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Example Document 5"))
        self.label_11.setText(_translate("MainWindow", "IBAN"))

